In [ ]:
pip uninstall transformers -y

In [ ]:
pip uninstall tokenizers -y

In [24]:
pip install -U datasets huggingface_hub

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.5)
Collecting datasets
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.2)
Collecting huggingface_hub
  Downloading huggingface_hub-1.19.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.4.6)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Collecting click>=8.4.0 (from huggingface_hub)
  Downloading click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface_hub)
  Downloading hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface_hub) (0.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<0.26.0,>=0.20.0->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<0.26.0,>=0.20.0->huggingface_hub) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<0.26.0,>=0.20.0->huggingface_hub) (0.1.2)
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 33.5 MB/s eta 0:00:00
Downloading huggingface_hub-1.19.0-py3-none-any.whl (693 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 693.4/693.4 kB 39.7 MB/s eta 0:00:00
Downloading click-8.4.1-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.6/116.6 kB 7.8 MB/s eta 0:00:00
Downloading hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 106.1 MB/s eta 0:00:0000:01
Installing collected packages: hf-xet, click, huggingface_hub, datasets
  Attempting uninstall: hf-xet
    Found existing installation: hf-xet 1.4.3
    Uninstalling hf-xet-1.4.3:
      Successfully uninstalled hf-xet-1.4.3
  Attempting uninstall: click
    Found existing installation: click 8.3.2
    Uninstalling click-8.3.2:
      Successfully uninstalled click-8.3.2
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface_hub 0.36.2
    Uninstalling huggingface_hub-0.36.2:
      Successfully uninstalled huggingface_hub-0.36.2
  Attempting uninstall: datasets
    Found existing installation: datasets 4.8.5
    Uninstalling datasets-4.8.5:
      Successfully uninstalled datasets-4.8.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
transformers 4.57.6 requires huggingface-hub<1.0,>=0.34.0, but you have huggingface-hub 1.19.0 which is incompatible.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
Successfully installed click-8.4.1 datasets-5.0.0 hf-xet-1.5.1 huggingface_hub-1.19.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip uninstall huggingface-hub -y

In [1]:
pip install "transformers<5.0.0"

Collecting transformers<5.0.0
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (3.25.2)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers<5.0.0)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5.0.0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5.0.0) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5.0.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5.0.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5.0.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5.0.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5.0.0) (2026.2.25)
Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 88.1 MB/s eta 0:00:00:00:0100:01
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 31.1 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.10.1
    Uninstalling huggingface_hub-1.10.1:
      Successfully uninstalled huggingface_hub-1.10.1
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed huggingface-hub-0.36.2 transformers-4.57.6
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install accelerate datasets torch

Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.5)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.36.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Collecting cuda-bindings==12.9.4 (from torch)
  Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 82.0 MB/s eta 0:00:00:00:010:01
Installing collected packages: cuda-bindings
  Attempting uninstall: cuda-bindings
    Found existing installation: cuda-bindings 13.2.0
    Uninstalling cuda-bindings-13.2.0:
      Successfully uninstalled cuda-bindings-13.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.
Successfully installed cuda-bindings-12.9.4
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install transformers[sentencepiece] datasets sacrebleu rouge_score py7zr -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.3/71.3 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 495.3/495.3 kB 29.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.6/100.6 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.5/51.5 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.3/144.3 kB 11.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install normalizer

Collecting normalizer
  Downloading normalizer-0.2.1.tar.gz (3.3 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from normalizer) (75.2.0)
Building wheels for collected packages: normalizer
  Building wheel for normalizer (setup.py) ... done
  Created wheel for normalizer: filename=normalizer-0.2.1-py3-none-any.whl size=3739 sha256=79a2d8351bf2b24455c200d9ec36ef13694c327587afc1365e3504f7acdd58d5
  Stored in directory: /root/.cache/pip/wheels/88/ed/80/2dcc547fc3ca3d4d5eff774cb7145f54f137dcad136c23e389
Successfully built normalizer
Installing collected packages: normalizer
Successfully installed normalizer-0.2.1
Note: you may need to restart the kernel to use updated packages.

In [5]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"  # only one GPU

In [6]:
import torch 
print(f"Visible Devices are {torch.cuda.device_count()}")
print(f"Visible Devices are {torch.cuda.get_device_name()}")

Visible Devices are 1
Visible Devices are Tesla T4

In [7]:
!nvidia-smi

Fri Jun 12 16:10:35 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       Off |   00000000:00:05.0 Off |                    0 |
| N/A   39C    P8             11W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [8]:
import torch
print(torch.cuda.is_available())

True

In [9]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

In [6]:
print(torch.cuda.device_count())

1

In [10]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.4.6)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (24.0.0)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.0 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6
Note: you may need to restart the kernel to use updated packages.

In [11]:
import transformers
from transformers import pipeline,set_seed
from datasets import load_dataset, load_from_disk
import matplotlib.pyplot as plt
import pandas as pd
from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from transformers import AutoModel
from transformers import AutoTokenizer, MT5ForConditionalGeneration
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.tokenize import sent_tokenize
from tqdm import tqdm
import torch

nltk.download("punkt")

2026-06-12 16:11:15.124653: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781280675.318572      58 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781280675.374719      58 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781280675.857144      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781280675.857187      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781280675.857190      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781280675.857193      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [67]:
data = pd.read_csv("/kaggle/input/datasets/hasanmoni/bengali-text-summarization/text_summarization.csv")

In [68]:
data.head(3)

,category,summary,text
0,technology,অ্যাপসে মিলবে ঢাকাসহ তিন জেলা আদালতের তথ্য,"ঢাকা মহানগর ও ঢাকা জেলা আদালত, কিশোরগঞ্জ ও রাঙ..."
1,bangladesh,বিজ্ঞান ও প্রকৌশলে মার্কিন সর্বোচ্চ সম্মাননা...,যুক্তরাষ্ট্রে বিজ্ঞান ও প্রকৌশলে পেশা শুরুর প...
2,bangladesh,বিকল্প শিশুখাদ্য গ্রহণে শিশুর মৃত্যু হলে শাস্ত...,বিকল্প শিশুখাদ্য ও বাণিজ্যিকভাবে উত্পাদিত শিশু...

In [10]:
data.shape

(80331, 3)

In [69]:
data.drop(["category"],axis=1,inplace=True)

In [ ]:
data.columns

In [70]:
data.isnull().sum()

summary    0
text       8
dtype: int64

In [71]:
data.dropna(inplace=True)

In [14]:
 data.duplicated

<bound method DataFrame.duplicated of                                                  summary  \
0             অ্যাপসে মিলবে ঢাকাসহ তিন জেলা আদালতের তথ্য
1      বিজ্ঞান ও প্রকৌশলে মার্কিন সর্বোচ্চ সম্মাননা...
2      বিকল্প শিশুখাদ্য গ্রহণে শিশুর মৃত্যু হলে শাস্ত...
3           ট্রেনে কাটা পড়ে সাবেক সিভিল সার্জনের মৃত্যু
4      যাত্রাবাড়ীতে চুলা জ্বালাতে গিয়ে দুই কর্মচারী ...
...                                                  ...
80326            ১০০ শয্যার হাসপাতালে জনবল ৫০ শয্যারও কম
80327  চট্টগ্রাম উত্তর ও দক্ষিণ বিএনপির দুই নেতাকে অব...
80328                হাতিয়ায় দুই লাশ দুই দিন ধরে পড়ে আছে
80329               বিয়ের আগে সম্পর্ক নিয়ে যা জানা দরকার
80330                  আরও আটটি বেড়া ও তিনটি টংঘর উচ্ছেদ

                                                    text
0      ঢাকা মহানগর ও ঢাকা জেলা আদালত, কিশোরগঞ্জ ও রাঙ...
1      যুক্তরাষ্ট্রে বিজ্ঞান ও প্রকৌশলে পেশা শুরুর প...
2      বিকল্প শিশুখাদ্য ও বাণিজ্যিকভাবে উত্পাদিত শিশু...
3      বগুড়ার আদমদীঘির সান্তাহারে গতকাল শনিবার ট্রেন...
4      যাত্রাবাড়ীর একটি রেস্তোরাঁয় গতকাল বুধবার ভোর...
...                                                  ...
80326  ঠাকুরগাঁও সদর হাসপাতালকে ১৬ বছর আগে ৫০ থেকে ১০...
80327  দলীয় শৃঙ্খলাবিরোধী কর্মকাণ্ডে জড়িত থাকার অভিযো...
80328  নোয়াখালীর দ্বীপ উপজেলা হাতিয়ার সুখচর ইউনিয়ন পর...
80329  বিয়ের ভাবনা ভাবছেন? তাহলে এই লেখাটি আপনার পড়া ...
80330  যশোর সদর উপজেলার ভৈরব নদের আরও সাড়ে চার কিলোমি...

[80323 rows x 2 columns]>

In [15]:
data.columns

Index(['summary', 'text'], dtype='object')

In [72]:
data = data.iloc[0:1000]

In [ ]:
dataset

In [73]:
data.shape

(1000, 2)

In [74]:
def semantic_dedup(sentences,embeding,threshold=0.85):
    keep = []
    keep_emb = []
    for i,sent in enumerate(sentences):
        if not keep:
            keep.append(sent)
            keep_emb.append(embeding[i])
            continue
        sim = cosine_similarity([embeding[i]],keep_emb).max()
        if sim < threshold:
            keep.append(sent)
            keep_emb.append(embeding[i])

    return keep

In [75]:
from sentence_transformers import SentenceTransformer

model =  SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

In [76]:
def clean_articles(text):
    sentence = str(text).split("|")
    embedding = model.encode(sentence)
    clean = semantic_dedup(sentence,embedding,0.85)
    return "|".join(clean)

In [77]:
data["clean_text"] = data["text"].apply(clean_articles)

In [ ]:
data["clean_text"][5]

In [78]:
import re

def full_clean_text(text):
    text = str(text)
    # remove unicode noise
    text = text.replace("\u200b",'')
    text = text.replace("\ufeff",'')
    text = text.replace("\u200c",'')
    text = text.replace("\u200d",'')
    # remove html tages
    text = re.sub(r"<.*?>","",text)
    # remove urls
    text = re.sub(r"http\S+|www\S+","",text)
    # normalize puctuation
    text = re.sub(r"\|+","|",text)
    text = re.sub(r"\?+","?",text)
    text = re.sub(r"!+","!",text)

    text = re.sub(r"\s+"," ",text).strip()
    return text

In [79]:
data['clean_text'] = data['clean_text'].apply(full_clean_text)

In [ ]:
data.head(4)

In [80]:
data["clean_text"][2]

'বিকল্প শিশুখাদ্য ও বাণিজ্যিকভাবে উত্পাদিত শিশুখাদ্য গ্রহণে কোনো শিশুর মৃত্যু বা স্বাস্থ্যহানি ঘটলে অথবা শিশু অসুস্থ হলে খাদ্য সরবরাহ বা প্রস্তুতকারী প্রতিষ্ঠানের বিরুদ্ধে দণ্ডবিধির আওতায় শাস্তিমূলক ব্যবস্থা নেওয়ার সুপারিশ করেছে স্বাস্থ্য মন্ত্রণালয়-সম্পর্কিত সংসদীয় কমিটি।এজন্য কমিটি সংসদে উত্থাপিত ‘মাতৃদুগ্ধ বিকল্প শিশুখাদ্য, বাণিজ্যিকভাবে প্রস্তুতকৃত শিশুর বাড়তি খাদ্য ও উহা ব্যবহারের সরঞ্জামাদি (বিপণন নিয়ন্ত্রণ, ইত্যাদি)’ বিলে এ-সম্পর্কিত একটি বিধান অন্তর্ভুক্ত করার সিদ্ধান্ত নিয়েছে। আজ মঙ্গলবার জাতীয় সংসদ ভবনে অনুষ্ঠিত কমিটির বৈঠকে এ সিদ্ধান্ত হয়।গত ১৬ জুলাই ‘মাতৃদুগ্ধ বিকল্প শিশুখাদ্য, বাণিজ্যিকভাবে প্রস্তুতকৃত শিশুর বাড়তি খাদ্য ও উহা ব্যবহারের সরঞ্জামাদি (বিপণন নিয়ন্ত্রণ, ইত্যাদি) বিল-২০১৩’ সংসদে উত্থাপিত হয়। পরে এটি পরীক্ষা করে প্রতিবেদন দেওয়ার জন্য সংসদীয় কমিটিতে পাঠানো হয়।বৈঠক শেষে কমিটির সভাপতি শেখ ফজলুল করিম সেলিম সাংবাদিকদের বলেন, বিকল্প শিশুখাদ্য গ্রহণের পর কোনো শিশুর ক্ষতি হলে খাদ্য সরবরাহকারী প্রতিষ্ঠানের বিরুদ্ধে ব্যবস্থা নেওয়ার বিধান বিলে নেই। তাই সংসদীয় কমিটি বিলে দণ্ডবিধি অনুযায়ী জরিমানা ও ক্ষতিপূরণ আদায়সহ অন্যান্য শাস্তির বিধান রাখতে বলেছে।প্রস্তাবিত আইনে বলা হয়েছে, বিকল্প শিশুখাদ্য, শিশুর বাড়তি খাদ্য মায়ের দুধের বিকল্প—এমন ধারণা দিয়ে কোনো ধরনের প্রচারণা চালানো যাবে না। এ ছাড়া বিকল্প শিশুখাদ্যের ওপর যেকোনো ধরনের বিজ্ঞাপন এবং শিশুখাদ্যের মোড়কে শিশু বা মায়ের ছবির ব্যবহার নিষিদ্ধ করা হয়েছে।কমিটির সভাপতি শেখ ফজলুল করিমের সভাপতিত্বে অনুষ্ঠিত বৈঠকে কমিটির সদস্য স্বাস্থ্যমন্ত্রী আ ফ ম রুহুল হক, স্বাস্থ্য প্রতিমন্ত্রী মজিবুর রহমান এবং মোহাম্মদ আমানউল্লাহ, জেড আই এম মোস্তফা আলী ও আমানুর রহমান খান অংশ নেন।'

In [54]:
import unicodedata
def normalize(text):
    if pd.isna(text):
        return text
    text = unicodedata.normalize("NFC",text)
    text = " ".join(text.split())
df['clean_text'] = df['clean_text'].apply(normalize)

In [81]:
data.head(5)

,summary,text,clean_text
0,অ্যাপসে মিলবে ঢাকাসহ তিন জেলা আদালতের তথ্য,"ঢাকা মহানগর ও ঢাকা জেলা আদালত, কিশোরগঞ্জ ও রাঙ...","ঢাকা মহানগর ও ঢাকা জেলা আদালত, কিশোরগঞ্জ ও রাঙ..."
1,বিজ্ঞান ও প্রকৌশলে মার্কিন সর্বোচ্চ সম্মাননা...,যুক্তরাষ্ট্রে বিজ্ঞান ও প্রকৌশলে পেশা শুরুর প...,যুক্তরাষ্ট্রে বিজ্ঞান ও প্রকৌশলে পেশা শুরুর প...
2,বিকল্প শিশুখাদ্য গ্রহণে শিশুর মৃত্যু হলে শাস্ত...,বিকল্প শিশুখাদ্য ও বাণিজ্যিকভাবে উত্পাদিত শিশু...,বিকল্প শিশুখাদ্য ও বাণিজ্যিকভাবে উত্পাদিত শিশু...
3,ট্রেনে কাটা পড়ে সাবেক সিভিল সার্জনের মৃত্যু,বগুড়ার আদমদীঘির সান্তাহারে গতকাল শনিবার ট্রেন...,বগুড়ার আদমদীঘির সান্তাহারে গতকাল শনিবার ট্রেন...
4,যাত্রাবাড়ীতে চুলা জ্বালাতে গিয়ে দুই কর্মচারী ...,যাত্রাবাড়ীর একটি রেস্তোরাঁয় গতকাল বুধবার ভোর...,যাত্রাবাড়ীর একটি রেস্তোরাঁয় গতকাল বুধবার ভোর...

In [82]:
model_ckpt = "csebuetnlp/banglat5"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

In [83]:
model_ckpt = "csebuetnlp/banglat5"
model = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

In [84]:
train = data

In [59]:
train.shape

(1000, 4)

In [ ]:
train.columns

In [85]:
train.drop(["text"],axis=1,inplace=True)

In [86]:
train.columns

Index(['summary', 'clean_text'], dtype='object')

In [ ]:
train.head(3)

In [87]:
from datasets import Dataset
dataset = Dataset.from_pandas(train)

In [88]:
dataset= dataset.train_test_split(test_size=0.2,seed=42)

In [37]:
dataset

DatasetDict({
    train: Dataset({
        features: ['summary', 'clean_text', '__index_level_0__'],
        num_rows: 800
    })
    test: Dataset({
        features: ['summary', 'clean_text', '__index_level_0__'],
        num_rows: 200
    })
})

In [ ]:
pip install git+https://github.com/csebuetnlp/normalizer

In [89]:
def convert_example_to_feature(example_batch,):
    
    inputs = ["summarize: " + text for text in example_batch['clean_text'] ]
    
    input_encoding = tokenizer(inputs,max_length=1024,padding= "max_length",truncation=True)
    
    target_encoding = tokenizer(text_target= example_batch['summary'],max_length=128,padding="max_length",truncation=True)
    labels = target_encoding["input_ids"]
    labels = [
        [(token if token!=tokenizer.pad_token_id else -100 ) for token in label]
        for label in labels
    ]
    

    return {
         "input_ids": input_encoding["input_ids"],
         "attention_mask": input_encoding["attention_mask"],
         "labels": labels
     }

In [90]:
# for huggingface dataset instead of apply we need to use map
tokenize_dataset = dataset.map(convert_example_to_feature,batched=True, remove_columns=['summary', 'clean_text', '__index_level_0__'])

Map:   0%|          | 0/800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

In [ ]:
tokenize_dataset

In [ ]:
tokenize_dataset['train']['labels'][1]  # Labels is summary vector Embedding

In [91]:
# Data Collator is for training the model using batch by batch dataset
from transformers import DataCollatorForSeq2Seq
seq2seqdatacollator = DataCollatorForSeq2Seq(tokenizer=tokenizer,model=model)

In [92]:
from transformers import Seq2SeqTrainingArguments
train_args = Seq2SeqTrainingArguments(
    output_dir = '/result',                       # where model checkpoints will be saved

    num_train_epochs = 3,                         # ❌ too low (use 2–5 for better summarization)

    per_device_train_batch_size = 1,              # batch size for training (Kaggle-safe)
    
    per_device_eval_batch_size = 1,               # batch size for evaluation
    
    weight_decay = 0.01,                          # regularization to reduce overfitting
    
    logging_steps=10,                             # log training loss every 10 steps


    eval_strategy="steps",                         # ⚠️ should be evaluation_strategy in newer versions
    
    eval_steps =100,                               # run evaluation every 100 steps
    
    save_steps =100,                               # save model every 100 steps
    
    learning_rate = 2e-5,                          # good learning rate for mT5 fine-tuning

    gradient_accumulation_steps= 1,                # simulate larger batch size if increased
    
    predict_with_generate= True,                     # 🔥 IMPORTANT: enables proper text generation eval
    
    warmup_steps = 200,                              # helps stabilize early training                            
    report_to=[],                                    # This disables all logging integrations
    
                                                     # or specifically: report_to="none"
    
    
    
)

In [93]:
from transformers import Seq2SeqTrainer
trainer = Seq2SeqTrainer(
    model=model,args=train_args,
    #tokenizer=tokenizer,
    data_collator=seq2seqdatacollator,
    train_dataset= tokenize_dataset["train"],
    eval_dataset = tokenize_dataset["test"]
    
)

In [94]:
trainer.train()

TrainOutput(global_step=2400, training_loss=5.852840372721354, metrics={'train_runtime': 1902.3983, 'train_samples_per_second': 1.262, 'train_steps_per_second': 1.262, 'total_flos': 3286835291750400.0, 'train_loss': 5.852840372721354, 'epoch': 3.0})

In [95]:
# Function for batch 
def generate_batch_size(list_of_elements, batch_size):
    for i in range(0,len(list_of_elements), batch_size):
        batch = list_of_elements[i:i+batch_size]
        yield batch # এখুনি ব্যাচ রিটার্ন করে, কিন্তু ফাংশন শেষ করে না

In [96]:
import evaluate
rouge = evaluate.load("rouge")

Downloading builder script: 0.00B [00:00, ?B/s]

In [97]:
def calculate_metric_on_test_ds(
    dataset,
    metric,
    model,
    tokenizer,
    batch_size,
    column_text="article",
    column_summary="highlights"
):
    articles_batch = list(
        generate_batch_size(dataset[column_text], 
                            batch_size)
    )
    targets_batch  = list(
        generate_batch_size(dataset[column_summary], 
                            batch_size)
    )
    model.eval()
    for articles,targets in tqdm(
        zip(articles_batch,targets_batch),
        total= len(articles_batch)
    ):
        inputs = tokenizer(
            articles,
            max_length=1024,
            padding= "max_length",
            truncation=True,
            return_tensors="pt"
        ).to(device) 
        with torch.no_grad():
            summarise = model.generate(
                input_ids = inputs["input_ids"],
                attention_mask= inputs["attention_mask"],
                length_penalty = 0.8,
                num_beams= 8,
                max_length=64,
                min_length =10
                
            ).to(device)
        decode_summarise=[
            tokenizer.decode(
                s,
                skip_special_tokens=True,
                clean_up_tokenization_spaces=True
                
            )
            for s in summarise
        ]
        decode_summarise = [
            summary.strip()
            for summary in decode_summarise
        ]
        targets = [
            str(t).strip()
            for t in targets
        ]
        metric.add_batch(
            predictions=decode_summarise, 
            references=targets
        )
    score = metric.compute()
    return score

In [98]:
score_1 = calculate_metric_on_test_ds(
    dataset['train'][0:100], rouge, trainer.model, tokenizer, batch_size = 2, column_text = 'clean_text', column_summary= 'summary'
)

100%|██████████| 50/50 [01:01<00:00,  1.22s/it]

In [ ]:
score_2 = calculate_metric_on_test_ds(
    dataset['test'][0:100], rouge, trainer.model, tokenizer, batch_size = 2, column_text = 'clean_text', column_summary= 'summary'
)

In [ ]:
score_1

In [99]:
rouge_names = ["rouge1", "rouge2", "rougeL", "rougeLsum"]
rouge_dict = dict({rn : score_1[rn] for rn in rouge_names })
pd.DataFrame(rouge_dict,index=["MT5_model_Bengali"])

                   rouge1  rouge2  rougeL  rougeLsum
MT5_model_Bengali     0.0     0.0     0.0        0.0

In [100]:
model.save_pretrained("csebuetnlp/banglat5for-Bangla")

In [101]:
tokenizer.save_pretrained("tokenizer")

('tokenizer/tokenizer_config.json',
 'tokenizer/special_tokens_map.json',
 'tokenizer/spiece.model',
 'tokenizer/added_tokens.json',
 'tokenizer/tokenizer.json')

# Prepare the model for evaluation

In [102]:
model.eval()

T5ForConditionalGeneration(
  (shared): Embedding(32128, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=768, out_features=32128, bias=False)
)

In [105]:
from transformers import MT5ForConditionalGeneration
path = "/kaggle/working/csebuetnlp/banglat5for-Bangla"
tokenizer = AutoTokenizer.from_pretrained("/kaggle/working/tokenizer")
model = AutoModelForSeq2SeqLM.from_pretrained(path)
model = model.to(device)

In [122]:
from transformers import pipeline
pipe = pipeline("summarization",model=model,tokenizer=tokenizer)

gen_args = {
    "length_penalty": 1.8,
    "num_beams": 8, 
    "max_length": 128,
    "min_length": 10,
    "no_repeat_ngram_size": 3,
    "early_stopping": True
}
test_dialogue = dataset["train"][690]['clean_text']
test_summary = dataset["train"][690]['summary']

print(f"original Dialogue: {test_dialogue}")
print("\n")
print(f"original Summary: {test_summary}")
print("\n")
print(f"Predicted Summary: {pipe("summarize news: " + test_dialogue, **gen_args)[0]["summary_text"]}")

Device set to use cuda:0
Both `max_new_tokens` (=256) and `max_length`(=128) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

original Dialogue: ‘পুলিশ পিটিয়ে আমার দুই হাত ভেঙে ফেলেছে। আমার ওপর অমানুষিক নির্যাতন চালিয়েছে, যা ভাষায় প্রকাশ করার নয়। আমি এর সুষ্ঠু বিচার চাই।’ কথাগুলো মো. নাদেরের। তাঁকে বংশাল থানার পুলিশ দুই মাস আগের বিস্ফোরক আইনের মামলায় গত মঙ্গলবার রাতে গ্রেপ্তার করে গতকাল বুধবার ঢাকার আদালতে পাঠায়।পুলিশ নাদেরের সাত দিনের রিমান্ড চাইলেও অসুস্থতার কথা বিবেচনা করে ঢাকার মহানগর হাকিম মো. ফাহাদ বিন আমিন চৌধুরী তাঁকে কারাগারে পাঠানোর আদেশ দেন। রিমান্ড শুনানির জন্য ১৪ ফেব্রুয়ারি দিন ঠিক করা হয়েছে।নাদেরকে গতকাল বিকেলে আদালতে হাজির করেন বংশাল থানার পুলিশ কনস্টেবল মশিউর রহমান। দেখা যায়, নাদেরের দুই হাতে ব্যান্ডেজ। ডান হাতে হাতকড়া পরানো।নাদেরের ওপর পুলিশের নির্যাতনের অভিযোগ সম্পর্কে মামলার তদন্ত কর্মকর্তা বংশাল থানার উপপরিদর্শক (এসআই) মো. আসাদুজ্জামান প্রথম আলোকে বলেন, গ্রেপ্তারের সময় পুলিশের সঙ্গে তাঁর ধস্তাধস্তি হয়েছিল। তবে কে তাঁর হাত ভেঙেছে, তা তিনি বলতে পারবেন না। আদালতের কাছে নাদেরের আইনজীবী শরীফ উদ্দিন লিখিত অভিযোগ করে বলেছেন, পুলিশ নির্যাতন করে তাঁর হাত ভেঙে দিয়েছে।মামলার এজাহারে পুলিশ বলেছে, নাদের বংশাল থানার ৩২ নম্বর ওয়ার্ড ছাত্রদলের সাবেক সভাপতি। তাঁর বাবার নাম জয়নুদ্দিন। তদন্ত কর্মকর্তা বলছেন, নাদের যুবদল করলেও এখন কোনো পদে নেই।নাদেরকে যে মামলায় গ্রেপ্তার করা হয়েছে, তা গত ডিসেম্বর মাসে করা। বংশাল থানার এসআই শহিদুল ইসলাম বাদী হয়ে বিস্ফোরক আইনে মামলা করেন। মামলার অভিযোগে বলা হয়, গত ৩ ডিসেম্বর বংশাল থানার হাজি ওসমান রোডের রাস্তার ওপর অস্ত্রশস্ত্র নিয়ে যানবাহন ভাঙচুর করা হয়। বিএনপির এক থেকে দেড় শ নেতা-কর্মী পুলিশ সদস্যদের হত্যার উদ্দেশে তাঁদের লক্ষ্য করে ইটপাটকেল, লাঠিসোঁটা ও ককটেল নিক্ষেপ করেন।রিমান্ডের আবেদনে পুলিশ বলেছে, আসামি বর্তমানে রাজনৈতিক পরিস্থিতি অস্থিতিশীল করার পাঁয়তারা করছেন বলে সাক্ষ্যপ্রমাণ পাওয়া যাচ্ছে।নাদেরকে যখন আদালত থেকে হাজতখানায় নেওয়া হচ্ছিল তখন তিনি বলছিলেন, ‘আমি পুলিশি নির্যাতনের শিকার।’


original Summary: ভাঙা হাতে আদালতে যুবক, পুলিশ বলল ধস্তাধস্তি


Predicted Summary: পুলিশ পিটিয়ে আমার দুই হাত ভেঙে ফেলেছে আমি এর সুষ্ঠু বিচার চাই

In [108]:
from transformers import pipeline
pipe = pipeline("summarization",model=model,tokenizer=tokenizer)

gen_args = {
    "length_penalty": 1.8,
    "num_beams": 8, 
    "max_length": 128,
    "min_length": 10,
    "no_repeat_ngram_size": 3,
    "early_stopping": True
}
text = """
মার্কিন সেন্ট্রাল কমান্ড (সেন্টকম) জানিয়েছে, তারা টানা দ্বিতীয় দিনের মতো 'আত্মরক্ষামূলক হামলা' সম্পন্ন করেছে। স্থানীয় সময় বৃহস্পতিবার ভোর রাতে এই হামলা চালানো হয়।

ইরানের ওপর 'কঠোর' আঘাত করা হবে এবং যুদ্ধ শেষ করার চুক্তিতে পৌঁছাতে তেহরান "খুব বেশি সময় নিচ্ছে"- যুক্তরাষ্ট্রের প্রেসিডেন্ট ডোনাল্ড ট্রাম্প এই কথা বলার পর সর্বশেষ মার্কিন হামলাটি চালানো হয়।

এর জবাবে ইরান জানিয়েছে, তারা বাহরাইন ও কুয়েতে অবস্থিত মার্কিন সামরিক ঘাঁটিতে হামলা চালিয়েছে; এর আগের দিনও ইরানের প্রতিশোধমূলক হামলায় এই দুটি ঘাঁটিই লক্ষ্যবস্তু ছিল।

সম্প্রতি পাল্টাপাল্টি হামলার তীব্রতা বৃদ্ধি পাওয়ায় এপ্রিলে দুই দেশের মধ্যে স্বাক্ষরিত ভঙ্গুর যুদ্ধবিরতিটি পরীক্ষার মুখে পড়েছে। সর্বশেষ মার্কিন হামলার পর, হরমুজ প্রণালির নিকটবর্তী ইরানের দক্ষিণাঞ্চলের শহরগুলোতে বিস্ফোরণের শব্দ শোনা গেছে, যেখানে মার্কিন বাহিনী আগের দফার হামলায় বিমান প্রতিরক্ষা, রাডার এবং অন্যান্য স্থাপনাতেও আঘাত হেনেছিল।

ইরানের রাষ্ট্রীয় গণমাধ্যম জানিয়েছে, এই সর্বশেষ উত্তেজনার মুহূর্তে দেশটির ইসলামিক রেভল্যুশনারি গার্ডস কোর (আইআরজিসি) হরমুজ প্রণালি দিয়ে যাওয়া দুটি তেল ট্যাংকারে হামলা চালিয়েছে, যদিও তাৎক্ষণিকভাবে খবরটি সম্পর্কে নিশ্চিত হওয়া যায়নি।

ইরানের রাষ্ট্রীয় গণমাধ্যমে হরমুজ প্রণালিকে "সব ধরনের জাহাজের জন্য সম্পূর্ণভাবে বন্ধ" ঘোষণা করার খবর প্রচারের পর এই ঘটনাটি ঘটে।

"""


print(pipe("summarize news:" + text, **gen_args)[0]["summary_text"])

Device set to use cuda:0
Both `max_new_tokens` (=256) and `max_length`(=128) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

মার্কিন কেন্দ্রীয় কমান্ড (সেন্টকম) জানিয়েছে, তারা টানা দ্বিতীয় দিনের মতো 'আত্মরক্ষামূলক হামলা' সম্পন্ন করেছে

In [148]:
test_dialogue = dataset["train"][550]['clean_text']
test_summary = dataset["train"][550]['summary']
print(f"Original Articles are: {test_dialogue}")
print("\n")
print(f"Original summarization: {test_summary}")

Original Articles are: সেনা বিদ্রোহে উসকানি দেওয়ার অভিযোগে গুলশান থানায় করা মামলায় নাগরিক ঐক্যের আহ্বায়ক মাহমুদুর রহমান মান্নাকে হাইকোর্টের দেওয়া জামিন স্থগিত করেছেন আপিল বিভাগ। পাশাপাশি ২৭ নভেম্বরের মধ্যে রাষ্ট্রপক্ষকে নিয়মিত লিভ টু আপিল করতে বলা হয়েছে।প্রধান বিচারপতি সুরেন্দ্র কুমার সিনহার নেতৃত্বাধীন তিন সদস্যের আপিল বিভাগ গতকাল সোমবার এ আদেশ দেন।১০ নভেম্বর হাইকোর্টের একটি দ্বৈত বেঞ্চ ওই মামলায় মান্নাকে জামিন দেন। এতে স্থগিতাদেশ চেয়ে রাষ্ট্রপক্ষ আবেদন করে। চেম্বার বিচারপতির আদালত হয়ে আবেদনটি গতকাল নিয়মিত বেঞ্চে শুনানির জন্য আসে।আদালতে রাষ্ট্রপক্ষে শুনানি করেন ভারপ্রাপ্ত অ্যাটর্নি জেনারেল মুরাদ রেজা। মান্নার পক্ষে ছিলেন আইনজীবী ইদ্রিসুর রহমান।সেনা বিদ্রোহে উসকানির ও রাষ্ট্রদ্রোহের অভিযোগে গত বছরের ২৪ ফেব্রুয়ারি ও ৫ মার্চ গুলশান থানায় মান্নার বিরুদ্ধে পৃথক মামলা হয়। নিউইয়র্কে অবস্থানরত বিএনপির ভাইস চেয়ারম্যান সাদেক হোসেন খোকা এবং অন্য এক ব্যক্তির সঙ্গে মান্নার ফোনালাপের দুটি অডিও ক্লিপ প্রকাশের পর গত বছরের ২৫ ফেব্রুয়ারি মান্নাকে গ্রেপ্তার করা হয়।


Original summarization: উসকানির অভিযোগে করা মামলায় মান্নার জামিন স্থগিত

In [149]:
inputs = tokenizer(
            test_dialogue,
            max_length=1024,
            padding= "max_length",
            truncation=True,
             return_tensors="pt"
            
)

In [ ]:
inputs.items()

In [150]:
inputs = {k:v.to(device) for k,v in inputs.items()}

In [151]:
inputs

{'input_ids': tensor([[2487, 6634,   10,  ...,    0,    0,    0]], device='cuda:0'),
 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0]], device='cuda:0')}

In [152]:
summarise_ids = model.generate(
    inputs["input_ids"],
    attention_mask= inputs["attention_mask"],
    length_penalty = 1.8,
    num_beams= 8,
    max_length=128,
    min_length =10,
    no_repeat_ngram_size = 3,
    early_stopping = True
)

summary =tokenizer.decode(summarise_ids[0],skip_special_tokens=True)

In [153]:
print(summary)

নাগরিক ঐক্যের আহ্বায়ক মাহমুদুর রহমান মান্নার জামিন স্থগিত করেছেন আপিল বিভাগ। ২৭ নভেম্বরের মধ্যে রাষ্ট্রপক্ষকে লিভ টু আপিল করতে বলা হয়েছে

In [154]:
tokenizer.save_pretrained("my_tokenizer")
model.save_pretrained("my_model")

In [156]:
import shutil
shutil.make_archive(
    "/kaggle/working/my_model",
    "zip",
    "/kaggle/working/my_tokenizer"
    
)

'/kaggle/working/my_model.zip'