In [1]:
pip install "transformers<5.0.0"

Collecting transformers<5.0.0
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (3.25.2)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers<5.0.0)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5.0.0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5.0.0) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5.0.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5.0.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5.0.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5.0.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<5.0.0) (2026.2.25)
Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 90.4 MB/s eta 0:00:00:00:01:01
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 19.8 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.10.1
    Uninstalling huggingface_hub-1.10.1:
      Successfully uninstalled huggingface_hub-1.10.1
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed huggingface-hub-0.36.2 transformers-4.57.6
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.4.6)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (24.0.0)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.1 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install accelerate datasets torch

Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.5)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (26.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.36.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Collecting cuda-bindings==12.9.4 (from torch)
  Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 96.7 MB/s eta 0:00:00:00:01:01
Installing collected packages: cuda-bindings
  Attempting uninstall: cuda-bindings
    Found existing installation: cuda-bindings 13.2.0
    Uninstalling cuda-bindings-13.2.0:
      Successfully uninstalled cuda-bindings-13.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.
Successfully installed cuda-bindings-12.9.4
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install transformers[sentencepiece] datasets sacrebleu rouge_score py7zr -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.3/71.3 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 495.6/495.6 kB 16.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.6/100.6 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.5/51.5 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.3/144.3 kB 12.3 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.

In [5]:
!pip uninstall datasets -y
!pip install datasets==3.3.0

Found existing installation: datasets 4.8.5
Uninstalling datasets-4.8.5:
  Successfully uninstalled datasets-4.8.5
Collecting datasets==3.3.0
  Downloading datasets-3.3.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (2.4.6)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (24.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets==3.3.0)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (0.70.16)
Collecting fsspec<=2024.12.0,>=2023.1.0 (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets==3.3.0)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (3.13.5)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets==3.3.0) (6.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.0) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==3.3.0) (1.23.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets==3.3.0) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets==3.3.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==3.3.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==3.3.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==3.3.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==3.3.0) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==3.3.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==3.3.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==3.3.0) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==3.3.0) (1.17.0)
Downloading datasets-3.3.0-py3-none-any.whl (484 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.9/484.9 kB 9.3 MB/s eta 0:00:00ta 0:00:01
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.8 MB/s eta 0:00:00
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 14.9 MB/s eta 0:00:00
Installing collected packages: fsspec, dill, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
  Attempting uninstall: dill
    Found existing installation: dill 0.4.1
    Uninstalling dill-0.4.1:
      Successfully uninstalled dill-0.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
tpot 1.1.0 requires dill>=0.3.9, but you have dill 0.3.8 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.
Successfully installed datasets-3.3.0 dill-0.3.8 fsspec-2024.12.0

In [6]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"  # only one GPU

In [7]:
import torch 
print(f"Visible Devices are {torch.cuda.device_count()}")
print(f"Visible Devices are {torch.cuda.get_device_name()}")

Visible Devices are 1
Visible Devices are Tesla T4

In [8]:
!nvidia-smi

Wed Jun 17 12:46:24 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.04             Driver Version: 580.159.04     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla T4                       Off |   00000000:00:05.0 Off |                    0 |
| N/A   40C    P8             10W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [9]:
import torch
print(torch.cuda.is_available())

True

In [10]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

In [11]:
print(torch.cuda.device_count())

1

# Important Libraries

In [12]:
import transformers
from transformers import pipeline,set_seed
from datasets import load_dataset, load_from_disk
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from transformers import AutoModel
from transformers import AutoTokenizer, MT5ForConditionalGeneration
from sklearn.metrics.pairwise import cosine_similarity
import nltk
from nltk.tokenize import sent_tokenize
from tqdm import tqdm
import torch
import re

nltk.download("punkt")

2026-06-17 12:46:31.759222: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1781700391.998691      58 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1781700392.059899      58 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1781700392.591519      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781700392.591563      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781700392.591566      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1781700392.591569      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

# Dataset Loading

In [13]:
data = load_dataset("csebuetnlp/xlsum","bengali",trust_remote_code = True, split="train")

README.md: 0.00B [00:00, ?B/s]

xlsum.py: 0.00B [00:00, ?B/s]

data/bengali_XLSum_v2.0.tar.bz2:   0%|          | 0.00/13.0M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

In [14]:
data

Dataset({
    features: ['id', 'url', 'title', 'summary', 'text'],
    num_rows: 8102
})

# Converting Data to Pandas & Preprocessing

In [15]:
data = data.to_pandas()

In [16]:
data = data[:4000]

In [17]:
data.head(5)

,id,url,title,summary,text
0,news-54690291,https://www.bbc.com/bengali/news-54690291,দুর্গাপূজার সময়ে যেভাবে শোক পালন করেন 'মহিষাস...,হিন্দু বাঙালীরা যে সময়ে তাদের সবথেকে বড় উৎসব...,দুর্গাপুজায় মহিষাসুর বধ্যে মধ্য দিয়ে অশুভর ও...
1,news-50797621,https://www.bbc.com/bengali/news-50797621,রাশিয়ায় ক্ষমতার ২০ বছর যেভাবে কেটেছে ভ্লাদিম...,ভ্লাদিমির পুতিন তাঁর ক্ষমতায় থাকার ২০ বছর পূর...,গত ২০ বছরে তিনি রাশিয়ার প্রেসিডেন্ট এবং প্রধা...
2,news-46678346,https://www.bbc.com/bengali/news-46678346,সংসদ নির্বাচন: বরিশালে ছয়টি আসন কিন্তু সবার দ...,বাংলাদেশের দক্ষিণাঞ্চলীয় জেলা বরিশাল এখন তুমু...,বরিশাল সদরে চলছে নির্বাচনী প্রচার প্রচারণা। যদ...
3,news-51860832,https://www.bbc.com/bengali/news-51860832,সর্বকালের সর্বশ্রেষ্ঠ বাঙালি: বিবিসি বাংলার জর...,দু'হাজার চার সালে বিবিসি বাংলা একটি 'শ্রোতা জর...,রবীন্দ্রনাথ ঠাকুর রবীন্দ্রনাথ ঠাকুর বাঙালির কা...
4,56310420,https://www.bbc.com/bengali/56310420,৭ই মার্চের ভাষণ: ৫০ বছর আগে রেসকোর্স ময়দানে উ...,'ভাষণ শুরু আগে মাথার উপর দিয়ে বিমান আর হেলিকপ...,আর কুমিল্লা থেকে বাস ভাড়া করে অনেকের সাথে নিজ...

In [18]:
data.shape

(4000, 5)

In [19]:
data.columns

Index(['id', 'url', 'title', 'summary', 'text'], dtype='object')

In [20]:
data.isnull().sum()

id         0
url        0
title      0
summary    0
text       0
dtype: int64

In [21]:
data.drop(['id', 'url','title'],axis=1,inplace=True)

In [22]:
data.columns

Index(['summary', 'text'], dtype='object')

In [23]:
data["text"][1]

"গত ২০ বছরে তিনি রাশিয়ার প্রেসিডেন্ট এবং প্রধানমন্ত্রী হিসেবে দায়িত্ব পালন করেছেন। এ সময়ের মধ্যে ভূ-রাজনৈতিক সংকট যেমন তৈরি হয়েছে তেমনি বিশ্ব ক্রীড়াঙ্গনের সবচেয়ে বড় আসর অর্থাৎ বিশ্বকাপ ফুটবল টুর্নামেন্ট আয়োজন করেছে রাশিয়া। সাবেক সোভিয়েত ইউনিয়নের গোয়েন্দা সংস্থা কেজিবি'র একজন এজেন্ট ছিলেন ভ্লাদিমির পুতিন। ১৯৯৯ সালের ৩১ শে ডিসেম্বর তিনি যখন রাশিয়ার প্রেসিডেন্ট হলেন তখন মার্কিন যুক্তরাষ্ট্রের প্রেসিডেন্ট ছিলেন বিল ক্লিনটন। গত ২০ বছরে যুক্তরাষ্ট্রের তিন প্রেসিডেন্ট এবং ব্রিটেনের পাঁচজন প্রধানমন্ত্রী ক্ষমতায় আসা-যাওয়া করেছেন। বৈশ্বিক সংঘাত, দেশের অভ্যন্তরে নানা কেলেঙ্কারি থেকে শুরু করে খেলাধুলার আসর আয়োজন এবং নিজের প্রচারণার জন্য নানা ছবি - এ সবকিছুই আছে মি: পুতিনের এই ২০ বছরে। তাঁর ক্ষমতার ২০ বছরে সেসব দিকে দৃষ্টি দিয়েছে বিবিসি। আরো পড়ুন: উদারপন্থা 'অচল' হয়ে পড়েছে: পুতিন কেন র\u200d্যাপ সঙ্গীতের নিয়ন্ত্রণ নিতে চান পুতিন ট্রাম্প-পুতিন শীর্ষ বৈঠক: কেন এতো গুরুত্বপূর্ণ? ১৯৯৯ সালের অগাস্ট মাসে ভ্লাদিমির পুতিনকে প্রধানমন্ত্রী হিসেবে নিয়োগ করা হয়। বরিস ইয়েলেতসিনের বিদায়ের পর ৩১ শে ডিসেম্বর মি: পুতিন প্রেসিডেন্ট হন। কেজিবি'র সাবেক এ কর্মকর্তা ১৯৯৯ সালে যখন ক্ষমতাসীন হলেন তখন দ্বিতীয়বারের মতো চেচনিয়া যুদ্ধ শুরু করে রাশিয়া। কিছু এপার্টমেন্টে বোমা হামলার জবাবে সে অভিযান শুরু করে রাশিয়া। প্রেসিডেন্ট হিসেবে মি: পুতিনের সূচনা হয়েছিল রাশিয়ার অস্থির দক্ষিণাঞ্চলে সংঘাতের মধ্য দিয়ে। চেচনিয়ার রাজধানী গ্রোজনি অবরোধ করে রাখে রাশিয়ার সৈন্যরা। ২০০৩ সালে জাতিসংঘের এক প্রতিবেদনে গ্রোজনিকে বিশ্বের সবচেয়ে ধ্বংসপ্রাপ্ত শহর হিসেবে বর্ণনা করা হয়। ২০০০ সালের মার্চ মাসে মি: পুতিন চেচনিয়া সফর করেন। এরপর কয়েক বছর ধরে জঙ্গি হামলায় আক্রান্ত হয় রাশিয়া। এর মধ্যে অন্যতম ছিল ২০০৪ সালে বেসলান স্কুলে হামলা, যেখানে ৩৩০ জন নিহত হয়। এদের মধ্যে বেশিরভাগ ছিল শিশু। ২০০৯ সাল পর্যন্ত প্রেসিডেন্ট পুতিন চেচনিয়াতে যুদ্ধ শেষ করেননি। ২০০০ সালের মার্চ মাসে প্রেসিডেন্ট পুতিন প্রেসিডেন্ট নির্বাচনের মাধ্যমে আবারো সে পদে আসীন হন। এর কয়েক মাসের মধ্যেই তিনি ইমেজ সংকটে পড়েন। ২০০৪ সালে বেসলাস স্কুলে হামলায় নিহতদের প্রতি শোক করতে রাশিয়ার মন্ত্রীসভা এক মিনিট নিরবতা পালন করে। কার্স্ক সাবমেরিন বিপর্যয়ে ১১৮ জন নাবিক মারা যায়। ২০০০ সালের অগাস্ট মাসে যখন কার্স্ক সাবমেরিন বিপর্যয় ঘটে তখন নিহত নাবিকদের পরিবারকে বিষয়টি অবহিত করতে বেশ কয়েকদিন সময় লাগে। তখন মি: পুতিন তখন অবকাশ যাপনে কৃষ্ণ সাগরে ছিলেন। কিন্তু সাবমেরিন বিপর্যয়ের পর প্রথমদিকে তিনি অবকাশ যাপন থেকে ফিরে আসেননি। কার্স্ক সাবমেরিন কমান্ডারের পরিবারের সাথে দেখা করেন মি: পুতিন। ক্ষমতার প্রথম দশকে মি: পুতিনের সাথে পশ্চিমা নেতাদের সম্পর্ক ভালোই ছিল। যদিও তিনি পশ্চিমা দেশগুলোর পররাষ্ট্রনীতির সমালোচক ছিলেন। ২০০৬ সালে রাশিয়া প্রথমবারের মতো শিল্পোন্নত দেশগুলোর জোট 'জি এইট' সম্মেলনের আয়োজন করে। এর মাধ্যমে সে জোটে রাশিয়ার অন্তর্ভুক্তিও ঘটে। ২০০১ সালে ভ্লাদিমির পুতিনকে যুক্তরাষ্ট্র সফরের আমন্ত্রণ জানান মার্কিন প্রেসিডেন্ট জর্জ বুশ। রাশিয়ার সংবিধান অনুযায়ী মি: পুতিন প্রেসিডেন্ট হিসেবে পরপর তিন মেয়াদে থাকতে পারতেন না। সেজন্য ২০০৮ সালে তিনি চার বছরের জন্য প্রধানমন্ত্রী হন। সে সময় রাশিয়ার প্রেসিডেন্ট হন দিমিত্রি মেদভেদেভ। কিন্তু অনেকে মনে করতেন, মি: মেদভেদেভ ছিলেন মি: পুতিনের হাতের পুতুল। ২০০৩ সালে ইতালির প্রধানমন্ত্রী সিলভিও বার্লোসকুনি রাশিয়া সফর করেন। সে সফরে ইরাক পরিস্থিতি নিয়ে আলোচনা হয়। ব্রিটেনের রানী এলিজাবেথ ২০০৩ সালে মি: পুতিনকে ব্রিটেনে রাষ্ট্রীয় সফরে আমন্ত্রণ জানান। ১৮৭৪ সালের পর সেটাই ছিল রাশিয়ার কোন নেতার ব্রিটেন সফর। ২০০৬ সালে সেন্ট পিটার্সবার্গে অনুষ্ঠিত জি এইট সামিটে জর্জিয়া থেকে বিচ্ছিন্ন হওয়া সাউথ ওশেটিয়া অঞ্চলের কর্তৃত্ব ফিরে পাবার জন্য ২০০৮ সালে জর্জিয়া যখন সেখানে সৈন্য পাঠায়, তখন রাশিয়া জর্জিয়ার ভেতরে আক্রমণ করে। স্বল্প সময়ের যুদ্ধ ছিল পশ্চিমা দেশগুলোর জন্য মি: পুতিন সম্পর্কে একটি সতর্কবার্তা। ২০১৪ সালে রাশিয়া যখন পূর্ব ইউক্রেন আক্রমণ করে তখন পশ্চিমা নেতাদের সাথে রাশিয়ার সম্পর্ক তিক্ত হয়ে ওঠে। ইউক্রেন থেকে ক্রাইমিয়া দখল করে নেবার পর ইউরোপীয় ইউনিয়ন এবং যুক্তরাষ্ট্র রাশিয়ার উপর অবরোধ আরোপ করে। এছাড়া শিল্পোন্নত দেশগুলোর সংগঠন 'জি এইট' থেকে রাশিয়ার সদস্যপদ স্থগিত করা হয়। জর্জিয়ার সাথে যুদ্ধ শুরু হলে, প্রধানমন্ত্রী হিসেবে আহতদের দেখতে যান মি: পুতিন। সিরিয়ার গৃহযুদ্ধ শুরু হবার চার বছর পরে প্রেসিডেন্ট বাশার আল আসাদকে রক্ষার জন্য রাশিয়া সে যুদ্ধে হস্তক্ষেপ করে। তখন প্রেসিডেন্ট বাশার আল আসাদ প্রায় পতনের মুখে চলে গিয়েছিলেন। সিরিয়াতে রাশিয়ার যুদ্ধ বিমান এবং সরঞ্জাম পাঠানোর কারণে সেখানকার ভারসাম্য বদলে যায়। মি: পুতিন যখন সিরিয়ার প্রেসিডেন্ট বাশার আল আসাদকে সমর্থন দেয়া শুরু করেন, তখন সিরিয়ার যুদ্ধের পরিস্থিতি বদলে যায়। ২০১৬ সালে মার্কিন প্রেসিডেন্ট নির্বাচনে ডোনাল্ড ট্রাম্প জয়লাভ করার পর মার্কিন গোয়েন্দা সংস্থা বলে যে, দেশটির প্রেসিডেন্ট নির্বাচনের প্রচারণায় রাশিয়া হস্তক্ষেপ করেছে। ২০১৮ সালে রাশিয়ার সাবেক সামরিক গোয়েন্দা কর্মকর্তা সার্গেই স্ক্রিপালকে ব্রিটেনের মাটিতে বিষ প্রয়োগে হত্যার জন্য রাশিয়াকে অভিযুক্ত করে ব্রিটেন। মার্কিন গোয়েন্দারা বলছে, যুক্তরাষ্ট্রে ২০১৬ সালের নির্বাচনে রাশিয়া হস্তক্ষেপ করেছে। সার্গেই স্ক্রিপালকে বিষ প্রয়োগে হত্যার পর ব্রিটেনের তখনকার প্রধানমন্ত্রী টেরিজা মে'র সাথে সম্পর্ক শীতল হয়। ২০১৪ সালে ইউক্রেনের ক্রাইমিয়া দখল করার পর দেশের ভেতরে মি: পুতিনের জনসমর্থন বাড়ে। ২০১৯ সালের অগাস্ট মাসে মি: পুতিন ক্রাইমিয়ায় মোটর সাইকেল র\u200d্যালিতে অংশ নেন। এটিকে সার্বভৈৗমত্বের লংঘন হিসেবে বর্ণনা করেছে ইউক্রেন। ইউক্রেন সংঘাত শুরুর পাঁচ বছর পর এ মাসে আলোচনা শুরু হয়। ক্ষমতায় থাকার পুরো সময় জুড়ে মি: পুতিন তাঁর নিজের এবং দেশের ইমেজ তুলে ধরার চেষ্টা করেছেন। নিজের কিছু ছবি দিয়ে প্রচারণার মাধ্যমে মি: পুতিন নিজেকে একজন শক্তিমান ব্যক্তি হিসেবে তুলে ধরতে চেয়েছেন। ২০০৭ সালে মঙ্গোলিয়ার সীমান্তে স্নাইপার হাতে হাঁটছেন ভ্লাদিমির পুতিন। ২০১৩ সালে পোষা কুকুকদের নিয়ে তুষাড়ের উপর খেলছেন মি: পুতিন। খেলাধুলায় নিজের পারদর্শিতা দেখানোর চেষ্টাও করেছেন মি: পুতিন। প্রেসিডেন্ট থাকা অবস্থায় আইস হকিতে অংশ নিয়েছেন। ২০১৪ সালে শীতকালীন অলিম্পিক এবং ২০১৮ সালে বিশ্বকাপ ফুটবল আয়োজনের মাধ্যমে মি: পুতিন ক্রীড়াঙ্গনে রাশিয়ার ভালো অবস্থান তুলে ধরতে চেয়েছেন। সোচিতে অনুষ্ঠিত শীতকালীন অলিম্পিক ছিল সফল। কিন্তু ডোপ কেলেঙ্কারির জের এখনো চলছে। ২০১৮ সালে বিশ্বকাপ ফুটবল আয়োজনের ক্ষেত্রে প্রেসিডেন্ট পুতিন গুরুত্বপূর্ণ ভূমিকা রেখেছেন। গত সপ্তাহে ওয়ার্ল্ড অ্যান্টি-ডোপিং এজেন্সি বা ওয়াডা রাশিয়াকে চার বছরের জন্য খেলাধুলার বড় আসরগুলোতে নিষিদ্ধ করেছে। রাশিয়ার বিরুদ্ধে ব্যাপকভাবে ডোপিং এর অভিযোগ ওঠে ২০১৫ সালে। সে বছরের নভেম্বরে রাশিয়ার অ্যান্টি ডোপিং সংস্থা 'রুসাডা' মাদক বন্ধে সহযোগিতা করছে না বলে ঘোষণা করে ওয়াডা। সংস্থার এক রিপোর্টে তখন বলা হয়েছিল, রাশিয়ায় সরকারি মদদেই ট্র্যাক অ্যান্ড ফিল্ড অ্যাথলেটিক্সে ব্যাপকভাবে মাদক ব্যবহৃত হচ্ছে। এরপর ২০১৬ সালে প্রকাশিত প্রতিবেদনে বলা হয়, রাশিয়ায় সরকারি পৃষ্ঠপোষকতায় চার বছর ধরে ডোপিং কর্মসূচি চলেছে যাতে করে তাদের প্রতিযোগীরা গ্রীষ্মকালীন এবং শীতকালীন অলিম্পিকসে অংশগ্রহণ করতে পারে। ২০১৯ সালের জানুয়ারিতে তারা ল্যাবরেটরি পরীক্ষার যেসব তথ্য হস্তান্তর করেছিল, তাতে কারসাজি করা হয় বলে অভিযোগ করছে ওয়াডা। তবে ২০১৮ সালের বিশ্বকাপ ফুটবল টুর্নামেন্ট আয়োজনে রাশিয়া ছিল সফল। ডোপিং কেলেঙ্কারির জন্য ২০২০ সালের টোকিও অলিম্পিকস এবং ২০২২ সালের কাতার বিশ্বকাপ ফুটবলে রাশিয়া অংশ নিতে পারবে না।"

In [24]:
data['summary'][1]

'ভ্লাদিমির পুতিন তাঁর ক্ষমতায় থাকার ২০ বছর পূর্ণ করতে যাচ্ছেন।'

# Function to remove similar lines in Data using Cosine Similarity

In [25]:
def semantic_dedup(sentences,embeding,threshold=0.50):
    keep = []
    keep_emb = []
    for i,sent in enumerate(sentences):
        if not keep:
            keep.append(sent)
            keep_emb.append(embeding[i])
            continue
        sim = cosine_similarity([embeding[i]],keep_emb).max()
        if sim < threshold:
            keep.append(sent)
            keep_emb.append(embeding[i])

    return keep

In [26]:
from sentence_transformers import SentenceTransformer

model =  SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [30]:
def clean_articles(text):
    sentence = str(text).split("|")
    embedding = model.encode(sentence)
    clean = semantic_dedup(sentence,embedding,0.50)
    return "|".join(clean)

In [31]:
data['text'] = data['text'].apply(clean_articles)

# Function For Cleaning Dataset

In [32]:
def full_clean_text(text):
    text = str(text)
    # remove unicode noise
    text = text.replace("\u200b",'')
    text = text.replace("\ufeff",'')
    text = text.replace("\u200c",'')
    text = text.replace("\u200d",'')
    # remove html tages
    text = re.sub(r"<.*?>","",text)
    # remove urls
    text = re.sub(r"http\S+|www\S+","",text)
    # normalize puctuation
    text = re.sub(r"\|+","|",text)
    text = re.sub(r"\?+","?",text)
    text = re.sub(r"!+","!",text)

    text = re.sub(r"\s+"," ",text).strip()
    return text

In [33]:
data['clean_text'] = data['text'].apply(full_clean_text)

In [34]:
data["clean_text"][1]

"গত ২০ বছরে তিনি রাশিয়ার প্রেসিডেন্ট এবং প্রধানমন্ত্রী হিসেবে দায়িত্ব পালন করেছেন। এ সময়ের মধ্যে ভূ-রাজনৈতিক সংকট যেমন তৈরি হয়েছে তেমনি বিশ্ব ক্রীড়াঙ্গনের সবচেয়ে বড় আসর অর্থাৎ বিশ্বকাপ ফুটবল টুর্নামেন্ট আয়োজন করেছে রাশিয়া। সাবেক সোভিয়েত ইউনিয়নের গোয়েন্দা সংস্থা কেজিবি'র একজন এজেন্ট ছিলেন ভ্লাদিমির পুতিন। ১৯৯৯ সালের ৩১ শে ডিসেম্বর তিনি যখন রাশিয়ার প্রেসিডেন্ট হলেন তখন মার্কিন যুক্তরাষ্ট্রের প্রেসিডেন্ট ছিলেন বিল ক্লিনটন। গত ২০ বছরে যুক্তরাষ্ট্রের তিন প্রেসিডেন্ট এবং ব্রিটেনের পাঁচজন প্রধানমন্ত্রী ক্ষমতায় আসা-যাওয়া করেছেন। বৈশ্বিক সংঘাত, দেশের অভ্যন্তরে নানা কেলেঙ্কারি থেকে শুরু করে খেলাধুলার আসর আয়োজন এবং নিজের প্রচারণার জন্য নানা ছবি - এ সবকিছুই আছে মি: পুতিনের এই ২০ বছরে। তাঁর ক্ষমতার ২০ বছরে সেসব দিকে দৃষ্টি দিয়েছে বিবিসি। আরো পড়ুন: উদারপন্থা 'অচল' হয়ে পড়েছে: পুতিন কেন র্যাপ সঙ্গীতের নিয়ন্ত্রণ নিতে চান পুতিন ট্রাম্প-পুতিন শীর্ষ বৈঠক: কেন এতো গুরুত্বপূর্ণ? ১৯৯৯ সালের অগাস্ট মাসে ভ্লাদিমির পুতিনকে প্রধানমন্ত্রী হিসেবে নিয়োগ করা হয়। বরিস ইয়েলেতসিনের বিদায়ের পর ৩১ শে ডিসেম্বর মি: পুতিন প্রেসিডেন্ট হন। কেজিবি'র সাবেক এ কর্মকর্তা ১৯৯৯ সালে যখন ক্ষমতাসীন হলেন তখন দ্বিতীয়বারের মতো চেচনিয়া যুদ্ধ শুরু করে রাশিয়া। কিছু এপার্টমেন্টে বোমা হামলার জবাবে সে অভিযান শুরু করে রাশিয়া। প্রেসিডেন্ট হিসেবে মি: পুতিনের সূচনা হয়েছিল রাশিয়ার অস্থির দক্ষিণাঞ্চলে সংঘাতের মধ্য দিয়ে। চেচনিয়ার রাজধানী গ্রোজনি অবরোধ করে রাখে রাশিয়ার সৈন্যরা। ২০০৩ সালে জাতিসংঘের এক প্রতিবেদনে গ্রোজনিকে বিশ্বের সবচেয়ে ধ্বংসপ্রাপ্ত শহর হিসেবে বর্ণনা করা হয়। ২০০০ সালের মার্চ মাসে মি: পুতিন চেচনিয়া সফর করেন। এরপর কয়েক বছর ধরে জঙ্গি হামলায় আক্রান্ত হয় রাশিয়া। এর মধ্যে অন্যতম ছিল ২০০৪ সালে বেসলান স্কুলে হামলা, যেখানে ৩৩০ জন নিহত হয়। এদের মধ্যে বেশিরভাগ ছিল শিশু। ২০০৯ সাল পর্যন্ত প্রেসিডেন্ট পুতিন চেচনিয়াতে যুদ্ধ শেষ করেননি। ২০০০ সালের মার্চ মাসে প্রেসিডেন্ট পুতিন প্রেসিডেন্ট নির্বাচনের মাধ্যমে আবারো সে পদে আসীন হন। এর কয়েক মাসের মধ্যেই তিনি ইমেজ সংকটে পড়েন। ২০০৪ সালে বেসলাস স্কুলে হামলায় নিহতদের প্রতি শোক করতে রাশিয়ার মন্ত্রীসভা এক মিনিট নিরবতা পালন করে। কার্স্ক সাবমেরিন বিপর্যয়ে ১১৮ জন নাবিক মারা যায়। ২০০০ সালের অগাস্ট মাসে যখন কার্স্ক সাবমেরিন বিপর্যয় ঘটে তখন নিহত নাবিকদের পরিবারকে বিষয়টি অবহিত করতে বেশ কয়েকদিন সময় লাগে। তখন মি: পুতিন তখন অবকাশ যাপনে কৃষ্ণ সাগরে ছিলেন। কিন্তু সাবমেরিন বিপর্যয়ের পর প্রথমদিকে তিনি অবকাশ যাপন থেকে ফিরে আসেননি। কার্স্ক সাবমেরিন কমান্ডারের পরিবারের সাথে দেখা করেন মি: পুতিন। ক্ষমতার প্রথম দশকে মি: পুতিনের সাথে পশ্চিমা নেতাদের সম্পর্ক ভালোই ছিল। যদিও তিনি পশ্চিমা দেশগুলোর পররাষ্ট্রনীতির সমালোচক ছিলেন। ২০০৬ সালে রাশিয়া প্রথমবারের মতো শিল্পোন্নত দেশগুলোর জোট 'জি এইট' সম্মেলনের আয়োজন করে। এর মাধ্যমে সে জোটে রাশিয়ার অন্তর্ভুক্তিও ঘটে। ২০০১ সালে ভ্লাদিমির পুতিনকে যুক্তরাষ্ট্র সফরের আমন্ত্রণ জানান মার্কিন প্রেসিডেন্ট জর্জ বুশ। রাশিয়ার সংবিধান অনুযায়ী মি: পুতিন প্রেসিডেন্ট হিসেবে পরপর তিন মেয়াদে থাকতে পারতেন না। সেজন্য ২০০৮ সালে তিনি চার বছরের জন্য প্রধানমন্ত্রী হন। সে সময় রাশিয়ার প্রেসিডেন্ট হন দিমিত্রি মেদভেদেভ। কিন্তু অনেকে মনে করতেন, মি: মেদভেদেভ ছিলেন মি: পুতিনের হাতের পুতুল। ২০০৩ সালে ইতালির প্রধানমন্ত্রী সিলভিও বার্লোসকুনি রাশিয়া সফর করেন। সে সফরে ইরাক পরিস্থিতি নিয়ে আলোচনা হয়। ব্রিটেনের রানী এলিজাবেথ ২০০৩ সালে মি: পুতিনকে ব্রিটেনে রাষ্ট্রীয় সফরে আমন্ত্রণ জানান। ১৮৭৪ সালের পর সেটাই ছিল রাশিয়ার কোন নেতার ব্রিটেন সফর। ২০০৬ সালে সেন্ট পিটার্সবার্গে অনুষ্ঠিত জি এইট সামিটে জর্জিয়া থেকে বিচ্ছিন্ন হওয়া সাউথ ওশেটিয়া অঞ্চলের কর্তৃত্ব ফিরে পাবার জন্য ২০০৮ সালে জর্জিয়া যখন সেখানে সৈন্য পাঠায়, তখন রাশিয়া জর্জিয়ার ভেতরে আক্রমণ করে। স্বল্প সময়ের যুদ্ধ ছিল পশ্চিমা দেশগুলোর জন্য মি: পুতিন সম্পর্কে একটি সতর্কবার্তা। ২০১৪ সালে রাশিয়া যখন পূর্ব ইউক্রেন আক্রমণ করে তখন পশ্চিমা নেতাদের সাথে রাশিয়ার সম্পর্ক তিক্ত হয়ে ওঠে। ইউক্রেন থেকে ক্রাইমিয়া দখল করে নেবার পর ইউরোপীয় ইউনিয়ন এবং যুক্তরাষ্ট্র রাশিয়ার উপর অবরোধ আরোপ করে। এছাড়া শিল্পোন্নত দেশগুলোর সংগঠন 'জি এইট' থেকে রাশিয়ার সদস্যপদ স্থগিত করা হয়। জর্জিয়ার সাথে যুদ্ধ শুরু হলে, প্রধানমন্ত্রী হিসেবে আহতদের দেখতে যান মি: পুতিন। সিরিয়ার গৃহযুদ্ধ শুরু হবার চার বছর পরে প্রেসিডেন্ট বাশার আল আসাদকে রক্ষার জন্য রাশিয়া সে যুদ্ধে হস্তক্ষেপ করে। তখন প্রেসিডেন্ট বাশার আল আসাদ প্রায় পতনের মুখে চলে গিয়েছিলেন। সিরিয়াতে রাশিয়ার যুদ্ধ বিমান এবং সরঞ্জাম পাঠানোর কারণে সেখানকার ভারসাম্য বদলে যায়। মি: পুতিন যখন সিরিয়ার প্রেসিডেন্ট বাশার আল আসাদকে সমর্থন দেয়া শুরু করেন, তখন সিরিয়ার যুদ্ধের পরিস্থিতি বদলে যায়। ২০১৬ সালে মার্কিন প্রেসিডেন্ট নির্বাচনে ডোনাল্ড ট্রাম্প জয়লাভ করার পর মার্কিন গোয়েন্দা সংস্থা বলে যে, দেশটির প্রেসিডেন্ট নির্বাচনের প্রচারণায় রাশিয়া হস্তক্ষেপ করেছে। ২০১৮ সালে রাশিয়ার সাবেক সামরিক গোয়েন্দা কর্মকর্তা সার্গেই স্ক্রিপালকে ব্রিটেনের মাটিতে বিষ প্রয়োগে হত্যার জন্য রাশিয়াকে অভিযুক্ত করে ব্রিটেন। মার্কিন গোয়েন্দারা বলছে, যুক্তরাষ্ট্রে ২০১৬ সালের নির্বাচনে রাশিয়া হস্তক্ষেপ করেছে। সার্গেই স্ক্রিপালকে বিষ প্রয়োগে হত্যার পর ব্রিটেনের তখনকার প্রধানমন্ত্রী টেরিজা মে'র সাথে সম্পর্ক শীতল হয়। ২০১৪ সালে ইউক্রেনের ক্রাইমিয়া দখল করার পর দেশের ভেতরে মি: পুতিনের জনসমর্থন বাড়ে। ২০১৯ সালের অগাস্ট মাসে মি: পুতিন ক্রাইমিয়ায় মোটর সাইকেল র্যালিতে অংশ নেন। এটিকে সার্বভৈৗমত্বের লংঘন হিসেবে বর্ণনা করেছে ইউক্রেন। ইউক্রেন সংঘাত শুরুর পাঁচ বছর পর এ মাসে আলোচনা শুরু হয়। ক্ষমতায় থাকার পুরো সময় জুড়ে মি: পুতিন তাঁর নিজের এবং দেশের ইমেজ তুলে ধরার চেষ্টা করেছেন। নিজের কিছু ছবি দিয়ে প্রচারণার মাধ্যমে মি: পুতিন নিজেকে একজন শক্তিমান ব্যক্তি হিসেবে তুলে ধরতে চেয়েছেন। ২০০৭ সালে মঙ্গোলিয়ার সীমান্তে স্নাইপার হাতে হাঁটছেন ভ্লাদিমির পুতিন। ২০১৩ সালে পোষা কুকুকদের নিয়ে তুষাড়ের উপর খেলছেন মি: পুতিন। খেলাধুলায় নিজের পারদর্শিতা দেখানোর চেষ্টাও করেছেন মি: পুতিন। প্রেসিডেন্ট থাকা অবস্থায় আইস হকিতে অংশ নিয়েছেন। ২০১৪ সালে শীতকালীন অলিম্পিক এবং ২০১৮ সালে বিশ্বকাপ ফুটবল আয়োজনের মাধ্যমে মি: পুতিন ক্রীড়াঙ্গনে রাশিয়ার ভালো অবস্থান তুলে ধরতে চেয়েছেন। সোচিতে অনুষ্ঠিত শীতকালীন অলিম্পিক ছিল সফল। কিন্তু ডোপ কেলেঙ্কারির জের এখনো চলছে। ২০১৮ সালে বিশ্বকাপ ফুটবল আয়োজনের ক্ষেত্রে প্রেসিডেন্ট পুতিন গুরুত্বপূর্ণ ভূমিকা রেখেছেন। গত সপ্তাহে ওয়ার্ল্ড অ্যান্টি-ডোপিং এজেন্সি বা ওয়াডা রাশিয়াকে চার বছরের জন্য খেলাধুলার বড় আসরগুলোতে নিষিদ্ধ করেছে। রাশিয়ার বিরুদ্ধে ব্যাপকভাবে ডোপিং এর অভিযোগ ওঠে ২০১৫ সালে। সে বছরের নভেম্বরে রাশিয়ার অ্যান্টি ডোপিং সংস্থা 'রুসাডা' মাদক বন্ধে সহযোগিতা করছে না বলে ঘোষণা করে ওয়াডা। সংস্থার এক রিপোর্টে তখন বলা হয়েছিল, রাশিয়ায় সরকারি মদদেই ট্র্যাক অ্যান্ড ফিল্ড অ্যাথলেটিক্সে ব্যাপকভাবে মাদক ব্যবহৃত হচ্ছে। এরপর ২০১৬ সালে প্রকাশিত প্রতিবেদনে বলা হয়, রাশিয়ায় সরকারি পৃষ্ঠপোষকতায় চার বছর ধরে ডোপিং কর্মসূচি চলেছে যাতে করে তাদের প্রতিযোগীরা গ্রীষ্মকালীন এবং শীতকালীন অলিম্পিকসে অংশগ্রহণ করতে পারে। ২০১৯ সালের জানুয়ারিতে তারা ল্যাবরেটরি পরীক্ষার যেসব তথ্য হস্তান্তর করেছিল, তাতে কারসাজি করা হয় বলে অভিযোগ করছে ওয়াডা। তবে ২০১৮ সালের বিশ্বকাপ ফুটবল টুর্নামেন্ট আয়োজনে রাশিয়া ছিল সফল। ডোপিং কেলেঙ্কারির জন্য ২০২০ সালের টোকিও অলিম্পিকস এবং ২০২২ সালের কাতার বিশ্বকাপ ফুটবলে রাশিয়া অংশ নিতে পারবে না।"

In [35]:
data["summary"][1]

'ভ্লাদিমির পুতিন তাঁর ক্ষমতায় থাকার ২০ বছর পূর্ণ করতে যাচ্ছেন।'

# Tokenizer Loading For BanglaT5 Model

In [36]:
model_ckpt = "csebuetnlp/banglat5"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

tokenizer_config.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/1.11M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

# BanglaT5 Model Loading

In [37]:
model_ckpt = "csebuetnlp/banglat5"
model = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

pytorch_model.bin:   0%|          | 0.00/990M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

In [39]:
train.drop(["text"],axis=1,inplace=True)

In [38]:
train = data

# Converting the Dataset back into a transformers Dataset

In [46]:
from datasets import Dataset
dataset = Dataset.from_pandas(train)

# Splitting Dataset in Train & Test

In [47]:
dataset= dataset.train_test_split(test_size=0.2,seed=42)

In [48]:
dataset

DatasetDict({
    train: Dataset({
        features: ['summary', 'clean_text'],
        num_rows: 3200
    })
    test: Dataset({
        features: ['summary', 'clean_text'],
        num_rows: 800
    })
})

# Tokenizations function

In [49]:
def convert_example_to_feature(example_batch,):
    
    inputs = ["summarize: " + text for text in example_batch['clean_text'] ]
    
    input_encoding = tokenizer(inputs,max_length=768,padding= "max_length",truncation=True)
    
    target_encoding = tokenizer(text_target= example_batch['summary'],max_length=32,padding="max_length",truncation=True)
    labels = target_encoding["input_ids"]
    labels = [
        [(token if token!=tokenizer.pad_token_id else -100 ) for token in label]
        for label in labels
    ]
    

    return {
         "input_ids": input_encoding["input_ids"],
         "attention_mask": input_encoding["attention_mask"],
         "labels": labels
     }

In [50]:
# for huggingface dataset instead of apply we need to use map
tokenize_dataset = dataset.map(convert_example_to_feature,batched=True, remove_columns=['summary', 'clean_text'])

Map:   0%|          | 0/3200 [00:00<?, ? examples/s]

Map:   0%|          | 0/800 [00:00<?, ? examples/s]

In [51]:
model.config.dropout_rate = 0.3

# DataCollator For Batch

In [52]:
# Data Collator is for training the model using batch by batch dataset
from transformers import DataCollatorForSeq2Seq
seq2seqdatacollator = DataCollatorForSeq2Seq(tokenizer=tokenizer,model=model)

# Training Arguments

In [53]:
from transformers import Seq2SeqTrainingArguments
train_args = Seq2SeqTrainingArguments(
    output_dir = '/result',                       # where model checkpoints will be saved

    num_train_epochs = 3,                        # ❌ too low (use 2–5 for better summarization)
    optim = "adafactor",

    per_device_train_batch_size = 2,              # batch size for training (Kaggle-safe)
    
    per_device_eval_batch_size = 2,               # batch size for evaluation
    
    weight_decay = 0.01,                          # regularization to reduce overfitting

    
    logging_steps=10,                             # log training loss every 10 steps


    eval_strategy="steps",                         # ⚠️ should be evaluation_strategy in newer versions
    
    eval_steps =100,                               # run evaluation every 100 steps
    
    save_steps =100,                               # save model every 100 steps
    
    learning_rate = 5e-5,                          # good learning rate for mT5 fine-tuning
    label_smoothing_factor=0.1,

    gradient_accumulation_steps= 1,                # simulate larger batch size if increased
    
    predict_with_generate= True,                     # 🔥 IMPORTANT: enables proper text generation eval
    
    warmup_steps = 200,                              # helps stabilize early training                            
    report_to=[],                                    # This disables all logging integrations
    
                                                     # or specifically: report_to="none"
    
    
    
)

# Trainer

In [54]:
from transformers import Seq2SeqTrainer
trainer = Seq2SeqTrainer(
    model=model,args=train_args,
    #tokenizer=tokenizer,
    data_collator=seq2seqdatacollator,
    train_dataset= tokenize_dataset["train"],
    eval_dataset = tokenize_dataset["test"]
    
)

In [55]:
trainer.train()

TrainOutput(global_step=4800, training_loss=5.298403408527374, metrics={'train_runtime': 7196.8784, 'train_samples_per_second': 1.334, 'train_steps_per_second': 0.667, 'total_flos': 9860505875251200.0, 'train_loss': 5.298403408527374, 'epoch': 3.0})

# Process To Get Rouge Score of The Model (Followed a youtube Video For This)

In [59]:
# Function for batch 
def generate_batch_size(list_of_elements, batch_size):
    for i in range(0,len(list_of_elements), batch_size):
        batch = list_of_elements[i:i+batch_size]
        yield batch # এখুনি ব্যাচ রিটার্ন করে, কিন্তু ফাংশন শেষ করে না

In [56]:
import evaluate
rouge = evaluate.load("rouge")

Downloading builder script: 0.00B [00:00, ?B/s]

In [57]:
def calculate_metric_on_test_ds(
    dataset,
    metric,
    model,
    tokenizer,
    batch_size,
    column_text="clean_text",
    column_summary="Summary"
):
    articles_batch = list(
        generate_batch_size(dataset[column_text], 
                            batch_size)
    )
    targets_batch  = list(
        generate_batch_size(dataset[column_summary], 
                            batch_size)
    )
    model.eval()
    for articles,targets in tqdm(
        zip(articles_batch,targets_batch),
        total= len(articles_batch)
    ):
        inputs = tokenizer(
            articles,
            max_length=768,
            padding= "max_length",
            truncation=True,
            return_tensors="pt"
        ).to(device) 
        with torch.no_grad():
            summarise = model.generate(
                input_ids = inputs["input_ids"],
                attention_mask= inputs["attention_mask"],
                length_penalty = 0.8,
                num_beams= 8,
                max_length= 32,
                min_length = 20
                
            )
        decode_summarise=tokenizer.batch_decode(
                summarise,
                skip_special_tokens=True,
                clean_up_tokenization_spaces=True
         )
            
        
        decode_summarise = [
            summary.strip()
            for summary in decode_summarise
        ]

        
        targets = [
            str(t).strip()
            for t in targets
        ]
        metric.add_batch(
            predictions=decode_summarise, 
            references=targets
        )
    print("PRED:", decode_summarise[0])
    print("REF :", targets[0])
    
    score = metric.compute()
    return score

In [60]:
score_1 = calculate_metric_on_test_ds(
    dataset['train'][0:70], rouge, trainer.model, tokenizer, batch_size = 2, column_text = 'clean_text', column_summary= 'summary'
)

100%|██████████| 35/35 [00:44<00:00,  1.27s/it]

PRED: বাংলাদেশে ক্রিকেটার সাকিব আল হাসানকে নিয়ে যে বিতর্ক তৈরি হয়েছে, তা নিয়ে সামাজিক যোগাযোগ মাধ্যমে ব্যাপক আলোচনা চলছে।
REF : বিতর্ক যেন বাংলাদেশের মানুষের প্রিয় ক্রিকেটার সাকিব আল হাসানকে তাড়া করে ফিরছে। তাকে ঘিরে সর্বশেষ বিতর্ক ক'দিন আগে তার কলকাতায় যাওয়ার ঘটনা নিয়ে।

In [61]:
rouge_names = ["rouge1", "rouge2", "rougeL", "rougeLsum"]
rouge_dict = dict({rn : score_1[rn] for rn in rouge_names })
pd.DataFrame(rouge_dict,index=["T5_Model For Bengali Text"])

                           rouge1  rouge2  rougeL  rougeLsum
T5_Model For Bengali Text     0.0     0.0     0.0        0.0

# Saving Model & Tokenizer Parameters

In [62]:
model.save_pretrained("Modelbanglat5for-Bangla")

In [63]:
tokenizer.save_pretrained("tokenizer")

('tokenizer/tokenizer_config.json',
 'tokenizer/special_tokens_map.json',
 'tokenizer/spiece.model',
 'tokenizer/added_tokens.json',
 'tokenizer/tokenizer.json')

In [64]:
model.eval()

T5ForConditionalGeneration(
  (shared): Embedding(32128, 768)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 768)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
              (relative_attention_bias): Embedding(32, 12)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-11): 11 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=768, out_features=768, bias=False)
              (k): Linear(in_features=768, out_features=768, bias=False)
              (v): Linear(in_features=768, out_features=768, bias=False)
              (o): Linear(in_features=768, out_features=768, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseGatedActDense(
              (wi_0): Linear(in_features=768, out_features=2048, bias=False)
              (wi_1): Linear(in_features=768, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=768, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): NewGELUActivation()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=768, out_features=32128, bias=False)
)

# Testing or Inference Using Pipeline & Generate of Model

In [65]:
path = "/kaggle/working/Modelbanglat5for-Bangla"
tokenizer = AutoTokenizer.from_pretrained("/kaggle/working/tokenizer")
model = AutoModelForSeq2SeqLM.from_pretrained(path)
model = model.to(device)

In [66]:
test_dialogue = dataset["train"][1090]['clean_text']
test_summary = dataset["train"][1090]['summary']
print(f"Original Articles are: {test_dialogue}")
print("\n")
print(f"Original summarization: {test_summary}")

Original Articles are: ২০১৭ সালের একটি সমীক্ষায় দেখা গেছে চীনে যারা ইন্টারনেট ব্যবহার করে তাদের মধ্যে ২৫ শতাংশেরও কম কাজের ব্যাপারে যোগাযোগের মাধ্যম হিসাবে ইমেল ব্যবহার করে। যখন আমি কোর্স শেষ করলাম, প্রাপ্তবয়স্ক শিক্ষার্থীরা আমাকে বললেন তারা আমার সাথে যোগাযোগ রাখতে চান। তারা বললেন চীনা একটা অ্যাপ আমার কম্প্যুটারে ডাউনলোড করে নিতে, যার নাম QQ (কিউকিউ)। অনেকটা ফেসবুক মেসেঞ্জারের মত এই অ্যাপ। আমি তাদের বললাম ফেসবুকে অ্যাকাউন্ট খুলে নিতে (তখন চীনে ফেসবুক খোলা ছিল) আর আমাকে বন্ধু হিসাবে যোগ করে নিতে। আরও বললাম তোমাদের ইমেল করার ঠিকানাটাগুলোও দিও। কয়েকজন দিলেন। কিন্তু সেসব ইমেল ঠিকানা মনে রাখা খুব কঠিন, কারণ সেগুলো ছিল এরকম: zwpzjg59826@126.com. আমার মনে হয়েছিল ইমেল ঠিকানাগুলো খুবই অদ্ভুত। তবে ২০০৮ সালে এমনকি যুক্তরাজ্যেও লোকে উদ্ভট সব নাম দিয়ে ইমেল পরিচিতি বা ঠিকানা তৈরি করত। কিন্তু এর বেশ কয়েক বছর পর আমি ফ্রিলান্স সাংবাদিক হিসাবে কাজ করতে বেইজিং গেলাম। তখনও দেখলাম চীনে প্রায় কেউই ইমেল ব্যবহারে আগ্রহী নন। চীনে যোগাযোগের জন্য সবচেয়ে বেশি ব্যবহৃত ও জনপ্রিয় হল উইচ্যাট অ্যাপ প্রায়ই আমাকে খবর লেখার জন্য সংবাদ পাঠানো হতো আমার স্মার্টফোনের উইচ্যাট অ্যাপে। চীনে যোগাযোগের জন্য উইচ্যাট বিপুল জনপ্রিয় অ্যাপ। আমার খবর লেখা হলে, সেটাও আমি পাঠাতাম উইচ্যাটে। আমাকে লেখার জন্য পেমেন্টও দেয়া হতো উইচ্যাটের মাধ্যমে। এই মোবাইল অ্যাপ এতই কার্যকর এবং এত দ্রুত যে মনে হতো সব কিছু নিমেষে হয়ে যাচ্ছে। অ্যাপই প্রধান পশ্চিমের বহু দেশে বিশেষ করে কর্মস্থলে এবং যে কোন কাজের কারণে যোগাযোগের মাধ্যম হিসাবে সবার উপরে রাখা হয় ইমেলকে। আমেরিকা এবং ব্রিটেনে অনলাইনে যেসব কাজকর্ম হয় তাতে ইন্টারনেট ব্যবহারকারীদের মধ্যে যারা ইমেলে কাজকর্ম করেন তাদের সংখ্যা যথাক্রমে ৯০.৯% এবং ৮৬%। অনলাইন মানুষ যেসব কারণে ব্যবহার করে, যেমন কোন তথ্য, পণ্য এবং সেবা সম্পর্কে খোঁজখবর করা, ইন্টারনেটে ব্যাংকের লেনদেন, কেনাকাটা, ডিজিটাল ভিডিও দেখা, অডিও শোনা এবং সামাজিক মাধ্যম ব্যবহার করা- এই দুটি দেশে অর্থাৎ আমেরিকা ও ব্রিটেনে ইন্টারনেট ব্যবহারের ক্ষেত্রে সেখানে সবার উপরে রয়েছে ইমেলে যোগাযোগ। কিন্তু চীনে চিত্রটা পুরো আলাদা। আরও পড়তে পারেন: উইচ্যাট-এর মত অ্যাপগুলো দিয়ে অনেক কিছু করা সম্ভব। বাজারে কেনাকাটা করা সহ এই অ্যাপ ব্যবহার করে অনেক কিছু করা যায়। চীনের ভোক্তারা মোবাইল কী কাজে ব্যবহার করে, ডিলয়েট সংস্থা সে বিষয়ে একটি জরিপ চালিয়েছিল ২০১৮ সালে । তাতে দেখা গেছে চীনের মানুষ ইমেল খোলেন বিশ্বের অন্যান্য দেশের তুলনায় ২২% কম। চীনে উইচ্যাটই প্রধান। চীনে যারা স্মার্টফোন ব্যবহার করে তাদের ৭৯.১% নিয়মিত এই অ্যাপ ব্যবহার করে। আর চীনে বিভিন্ন মেসেজিং অ্যাপ ব্যবহারকারীদের মধ্যে ৮৪.৫%ই ব্যবহার করে উইচ্যাট। চীনারা ব্যক্তিগত কারণে, দৈনন্দিন কাজেই যে শুধু উইচ্যাট ব্যবহার করে তা নয়, অফিসের কাজকর্মেও তারা উইচ্যাট ব্যবহার করতে বেশি পছন্দ করে। উইচ্যাট অ্যাপটি তৈরি করেছে টেনসেন্ট নামে যে কোম্পানি তাদের গবেষণা বিভাগ পেঙ্গুইন ইন্টালিজেন্স বিশ হাজার ভোক্তার ওপর একটি জরিপ চালিয়ে দেখেছে প্রতিদিন কর্মস্থলে চীনের ৮৮% মানুষ উইচ্যাট ব্যবহার করছেন। ফোন, এসএমএস এবং টেক্সট তারা ব্যবহার করেন প্রায় ৬০% আর তৃতীয় স্থানে অর্থাৎ সবার নিচে আছে ইমেল - ২২.৬%। ইভা হ্যসু একটি ডিজিটাল ব্র্যান্ডিং কোম্পানি চালান। তিনি তাইওয়ানিজ, তরুণ বয়সে কয়েক বছর কাটিয়েছেন আমেরিকায়, গত ছয় বছর কাজ করছেন সাংহাইতে। তিনি বলছেন, বিদেশে তার যেসব ক্লায়েন্ট আছেন তাদের সাথে যোগাযোগের জন্য তিনি ইমেল বা লিংকডইন ব্যবহার করেন। কিন্তু চীনে যাদের সাথে ব্যবসা করেন, তাদের সাথে সব যোগাযোগ একদম আলাদা। "চীনা ক্লায়েন্টরা উইচ্যাটই ব্যবহার করেন। যত ফাইলপত্র সবই উইচ্যাটে পাঠান।" চীনে সাইবার ক্যাফের জনপ্রিয়তা বেড়েছে উইচ্যাট ব্যবহারের কারণে সাইবার ক্যাফে সংস্কৃতি চীনে ১০০ কোটির বেশি ব্যবহারকারীর জন্য উইচ্যাট একটি সুপারঅ্যাপ এবং এই অ্যাপ এখন চীনা জীবনের সবক্ষেত্রে। কিন্তু এই অ্যাপের প্রতি চীনের মানুষের নির্ভরতা এবং এর জনপ্রিয়তা তৈরি হয়েছে সম্ভবত বেশ কয়েক বছর আগে। উনিশশো নিরানব্বই সালে, সেসময় চীনে গড়ে ওঠা নতুন প্রযুক্তি কোম্পানি টেনসেন্ট বাজারে একটি নতুন পণ্য ছেড়েছিল- নাম কিউকিউ। সেটি ছিল কম্প্যুটারে বার্তা আদানপ্রদানের একটি মেসেজিং প্ল্যাটফর্ম। বিশ্বব্যাংকের হিসাব অনুযায়ী, সেসময় চীনে প্রতি ১০০ জনের মধ্যে গড়ে মাত্র ১.২ জন মানুষের কম্প্যুটার ছিল। ওই সময় আমেরিকায় প্রতি দুজনের মধ্যে একজনের কম্প্যুটার ছিল। কিন্তু ২০০০সাল থেকে চীনের সর্বত্র ব্যাঙের ছাতার মত গজিয়ে উঠল ইন্টারনেট ক্যাফে। এবং সেখানে তরুণদের ভিড় উপছে পড়তে শুরু করল। চীনে যারা ইন্টারনেট ব্যবহার করেন তাদের জন্য কিউকিউ-এর মত প্রোগ্রাম ইমেলের চেয়ে অনেক বেশি অর্থবহ হয়ে উঠল। দেশে ইন্টারনেটের ব্যবহার যত প্রসার লাভ করতে শুরু করল, এর জনপ্রিয়তাও ততই বাড়তে থাকল। এসব ক্যাফে জনপ্রিয় হয়ে উঠেছিল মূলত কিউকিউ-এর কারণে। কিউকিউ-এ কম্প্যুটারে গেম খেলা যেত, গানবাজনা শোনা যেত এবং চীনে সেই প্রথমদিকে সামাজিক যোগাযোগ মাধ্যমে ছোট ছোট ব্লগ লেখা যেত এই প্ল্যাটফর্মের মাধ্যমে। কিউকিউ ইমেলের চেয়ে বেশি ও সহজে দ্রুত যোগাযোগের সুযোগ করে দিয়েছিল মানুষকে। ইনস্টান্ট মেসেজিং বা অনলাইনে সরাসরি কথোপকথনের একটা পথ তখনই তৈরি করে দিয়েছিল কিউকিউ। ভবিষ্যতের চীনকে নিয়ে ২০০৮ সালে 'সুপারট্রেন্ডস অফ ফিউচার চায়না' বইয়ের লেখক জেমস ইউয়ান ও জেসন ইঞ্চ বলেছিলেন, চীনে কারো কিউকিউ নেই এটা ভাবাই যায় না। বড় বড় কোম্পানির ব্যবসায়ীরা তাদের বিজনেস কার্ডে কিউকিউ নম্বর ছাপাতেন। প্রত্যেক ব্যবসা প্রতিষ্ঠানের নিজস্ব কিউকিউ অ্যাকাউন্ট নম্বর ছিল। দুহাজার বারো সালের মধ্যে সক্রিয়ভাবে কিউকিউ ব্যবহারকারীর সংখ্যা দাঁড়িয়েছিল ৭৯ কোটি ৮০ লাখ, যা ছিল সেই বছর চীনের মোট জনসংখ্যার অর্ধেকের বেশি। উইচ্যাটের উদ্ভাবক প্রযুক্তি কোম্পানি টেনসেন্ট-এর প্রতিষ্ঠাতা মা হুয়াতেং। এই টেনসেন্ট কোম্পানিই ২০১১ সালে উদ্ভাবন করেছে উইচ্যাট অ্যাপ, যা চীনে এখন সবচেয়ে জনপ্রিয় যোগাযোগ মাধ্যম। একই সাথে চীনে কম্প্যুটার বিদায় নিচ্ছে, তার জায়গা নিচ্ছে স্মার্ট ফোন। চীনে ২০০৪ সাল থেকে ডিজিটাল উদ্ভাবন বিষয়ে উপদেষ্টা হিসাবে কাজ করছেন ব্রিটেনের ম্যাথিউ ব্রেনান। তিনি বলছেন, বহু দেশে ইমেল ঠিকানা থাকাটা মানুষের পরিচিতির একটা অংশ, কারণ অনলাইনে বিভিন্ন ধরনের সেবা নিতে গেলে তার জন্য নথিভুক্ত হতে ইমেল ঠিকানা ব্যবহার করতে হয়। কিন্তু চীনে মোবাইল অ্যাপের মাধ্যমে সব কিছু করা সম্ভব। 'উইচ্যাট' এবং আলিবাবার তৈরি অ্যাপ 'আলিপে'তে একবার লগ ইন করে বিভিন্ন ধরনের সেবা পাওয়া যায়, আলাদা আলাদা লগ ইন-এর প্রয়োজন হয় না-একটা অ্যাপের মাধ্যমেই অ্যাপয়েন্টমন্ট বুক করা থেকে শুরু করে, বাজার দোকান করা, অফিস বা ব্যবসা করা এবং বন্ধুদের সঙ্গে কথাবার্তা বলা সবই করা যায়- ইমেলের কোন প্রয়োজন হয় না। দ্রুত আদান-প্রদানের সংস্কৃতি চিউং কং গ্র্যাজুয়েট স্কুল ফর বিজনেসের অর্থনীতির অধ্যাপক ঝং লিং মনে করেন, চীনের কর্ম সংস্কৃতির সাথে উইচ্যাট খুবই সামঞ্জস্যপূর্ণ। তিনি বলছেন, এই চ্যাট অ্যাপে যে কোন সময়ে, যে কোন জায়গা থেকে যে কোন কাজ করা যায় - আপনাকে ব্যবসা বা অফিসের কাজের জন্য অফিসের সময়ের ওপর নির্ভর করতে হবে না। কোন কিছু চাইলে তার উত্তরের জন্য অপেক্ষা করতে হবে না, যা চাইছেন তা সাথে সাথে পাওয়া যাবে, যেটা চীনের সংস্কৃতি, মানসিকতা ও ব্যবসার পরিবেশের সাথে খুবই খাপ খায়। চীনে কাজের সময় আর ব্যক্তিগত সময়ের মধ্যে সীমারেখাাটা দুর্বল মিস ঝং বলছেন, চীনে মানুষের কাজের সময় আর ব্যক্তিগত সময়ের মধ্যে সীমানাটা বেশ দুর্বল। "ফলে চাকুরিদাতারা বা ম্যানেজাররা প্রায়ই কাজের সময়ের বাইরে প্রশ্ন জানতে চেয়ে কর্মচারীদের বার্তা পাঠান বা তাদের কাজ করতে বলেন। খুবই সামান্য একটা উত্তরের জন্যও তারা পরের দিন পর্যন্ত অপেক্ষা করা পছন্দ করেন না।" ইমেলে বার্তা আদান প্রদান করতে যে সময়টা দিতে হয়, তাতে হয়ত একটা বিষয় নিয়ে কয়েকবার মেইল চালাচালির প্রয়োজন হয়, কিন্তু উইচ্যাটে খুব দ্রুত ও সংক্ষিপ্ত কথোপকথনের মাধ্যমে কাজ করা যায়, বলছেন মিস ঝং। ফলে এই দ্রুত ও সহজ মেসেজিং অ্যাপ মানুষের ওপর সবসময় কাজ করার বাড়তি একটা চাপও তৈরি করেছে। ইনস্টান্ট মেসেজিংয়ে ইমেলের চেয়ে অনেক দ্রুত কথোপকথন সম্ভব দ্রুত উত্তরের যুগ যোগাযোগের একটা প্ল্যাটফর্ম যখন তৈরি হয় তখন তা ব্যবহারেরও একটা ধারা তৈরি হয়ে যায়। যেমন ফেসবুক, হোয়াটসঅ্যাপ - উইচ্যাটের মত এসব যোগাযোগ মাধ্যমেও কেউ কিছু জানতে চাইলে মানুষ সাথে সাথে উত্তর পাবে বলে আশা করে। মি. ব্রেনান বলছেন, ইমেল অনেকটা আনুষ্ঠানিক যোগাযোগের মাধ্যম - সেখানে মেইলের শুরুতে - প্রিয় বা সম্মানিত অমুক, ও শেষে- শ্রদ্ধান্তে বা শুভেচ্ছান্তে তমুক এবং এমনকী বয়ানেও অনেকটা পুরনো চিঠি লেখার স্টাইল অনুসরণ করা হয়। ফলে ইমেল লিখতে সময় লাগে। তিনি বলছেন, চীনে তো বটেই, এমনকি এশিয়ার অনেক দেশে এখন ইমেল বাদ দিয়ে চ্যাট অ্যাপ কাজের ক্ষেত্রে যোগাযোগের প্রধান মাধ্যম হয়ে উঠছে। কারণ চ্যাট অ্যাপে আনুষ্ঠানিক হবার প্রয়োজন নেই। দ্রুত প্রশ্ন পাঠানো এবং দ্রুত তার জবাব পাওয়াটাই সেখানে মুখ্য। প্রফেট নামে একটি উপদেষ্টা সংস্থা যারা এশিয়ার বিভিন্ন দেশে কাজ করে, তার একজন শীর্ষ কর্মকর্তা অ্যালান কেসি বলছেন, চীনের মতই দক্ষিণ পূর্ব এশিয়ার অনেক দেশ এখন কম্প্যুটার যুগকে পেছনে ফেলে মোবাইল ভিত্তিক অ্যাপের যুগে দ্রুত উত্তরণ ঘটাচ্ছে। এবং দ্রুত জনপ্রিয় হচ্ছে ফেসবুক, উইচ্যাট, লাইন, কাকাও টক এবং জেলোর মত বিভিন্ন সামাজিক প্ল্যাটফর্ম। ব্যবসা বান্ধব অ্যাপ চীনে উইচ্যাট ছাড়াও বড় বড় ব্যবসা প্রতিষ্ঠান এবং যারা আরও ব্যাপক পর্যায়ে কর্মীদের কাছ থেকে কাজ পেতে চান তাদের জন্য তৈরি হয়েছে ব্যবসা বান্ধব অ্যাপ। চীনে অনেক মানুষের ইমেল ঠিকানা আছে, কিন্তু তারা খুবই কালে ভদ্রে তাদের ইমেল অ্যাকাউন্ট খোলেন আলিবাবা তৈরি করেছে 'ডিংটক' বাইটডান্স তৈরি করেছে 'লার্ক', উইচ্যাটও বড় ব্যবসা প্রতিষ্ঠানের জন্য তৈরি করেছে 'উইচ্যাট ওয়ার্ক'। এসব অ্যাপের মাধ্যমে উঁচু পর্যায়ের নিরাপত্তা বজায় রেখে বড় বড় নথি শেয়ার করা যায়, অনলাইনে নথি রদবদল করা যায়, মানুষের বেতন সংক্রান্ত কাজকর্ম করা যায়। ডিংটক অ্যাপে সরাসরি দেখা যায় আপনার পাঠানো মেসেজ যিনি পেয়েছেন তিনি পড়েছেন কিনা, না পড়লে তাকে পড়ার জন্য আবার মেসেজ করা যায়। পশ্চিমের অবস্থা তিরিশ বছর বয়সী হেইলান জিয়া একটি চীনা ক্রিপটোকারেন্সি ব্যবসা প্রতিষ্ঠানের জনসংযোগ ম্যানেজার। তার স্বামীর সঙ্গে থাকার জন্য ২০১৮ সালে তিনি বেজিং থেকে ইংল্যান্ডে চলে এসেছেন। তিনি বলছেন, ব্রিটেনে অনলাইন সেবা খুবই ছড়ানো। একেকটা কাজের জন্য আপনাকে অনলাইনে একেকটা সেবা প্রতিষ্ঠানে লগ ইন করতে হবে। কিন্তু চীনে উইচ্যাটে গেলে সব কিছু একসাথে এক জায়গায় আছে। "আপনার উইচ্যাট অ্যাকাউন্ট থাকলে আপনি সব রকম কাজ এক অ্যাপ থেকেই করতে পারবেন।" "ইংল্যান্ডে আমাকে অনবরত ইমেল চেক করতে হয়, চীনে আমি কখনও ইমেল খুলতাম না, কেউ সেখানে ইমেল দেখে না। ইমেলে জবাব দেবার জন্য কোন প্রত্যাশাও সেখানে নেই," বলেন হেইলান জিয়া। তবে চীনে কেউ ইমেল একেবারেই ব্যবহার করে না সেটা ঠিক নয়। অনেকেরই ইমেল অ্যাকাউন্ট আছে, কিন্তু তারা ইমেল খুলে তা দেখেন খুবই অনিয়মিতভাবে। মি. ব্রেনান বলছেন, বেজিং এবং সাংহাইতে যারা কাজ করেন তারা যেহেতু আন্তর্জাতিক সংস্কৃতির সাথে বেশি পরিচিতি তারা তুলনামূলকভাবে বেশি ইমেল খোলেন। চীনে কি ইমেল এখন অতীতের ফেলে আসা প্রযুক্তি? আমার পুরনো শিক্ষার্থীরা গোড়াতেই যে বলছিলাম আমি যখন চীনে ইংরেজি শিক্ষকতা শেষ করেছিলাম আমার পুরনো শিক্ষার্থীদের বলেছিলাম যোগাযোগ রাখার জন্য তাদের ইমেল দিতে। এদের একজন ছিলেন ইয়াংশু লিলি ওয়াং। আমরা কিছুকাল ইমেলে যোগাযোগ রেখেছিলাম। তারপর আমাদের যোগাযোগ বন্ধ হয়ে যায়। এখন তার বয়স ৩০। দক্ষিণ চীনে গুয়াংডং-এ তিনি থাকেন। বছর দুয়েক আগে তাকে আমি উইচ্যাটে খুঁজে পাই। এখন উইচ্যাটে আমাদের কথা হয়। আমি তাকে জিজ্ঞেস করেছিলাম পুরনো সেই ইমেল অ্যাড্রেসটা কি তার এখনও আছে? সে জানতে চাইল কোনটা? হেসে বলল, "আমার তো অনেকগুলো ঠিকানা ছিল ১৬৩, ১২৬, এমএসএন।" সে বলল, শেষ কবে যে সে ইমেল ব্যবহার করেছে তার মনে পড়ে না। "এখন আমি উইচ্যাট ব্যবহার করি। কিউকিউ খুব একটা ব্যবহার করি না, মাঝে মাঝে করি," সে বলল। চীনে লিলি ওয়াংয়ের মত বেশির ভাগ মানুষের জীবনের একটা অবিচ্ছেদ্য অংশ এখন উইচ্যাট। ইমেল তাদের জন্য অতীতের কোন একটা প্রযুক্তি।


Original summarization: দক্ষিণ চীনের একটি ছোট শহর ইয়াংশুর একটি বেসরকারি ইংরেজি মাধ্যম স্কুলে আমি ২০০৮ সালের মে মাসে শিক্ষকতা করতে গিয়েছিলাম।

In [ ]:
test_dialogue= """
নারী ফুটবলের ইতিহাসে ২০২৩ সালের নারী বিশ্বকাপ ছিল স্পেনের জন্য স্বপ্নপূরণের মুহূর্ত। প্রথমবারের মতো বিশ্ব চ্যাম্পিয়ন হয়েছিল দেশটি। কিন্তু সেই ঐতিহাসিক জয়কে ছাপিয়ে বিশ্বজুড়ে আলোচনার কেন্দ্রে চলে আসে একটি চুম্বন—যে চুম্বন শুধু একজন ফুটবলারের ব্যক্তিগত সীমারেখা লঙ্ঘন করেনি, বরং স্পেনের ক্রীড়া প্রশাসন, ক্ষমতার অপব্যবহার এবং নারীদের প্রতি আচরণ নিয়ে এক অভূতপূর্ব সামাজিক আন্দোলনের জন্ম দিয়েছিল।
সেই ঘটনাকেই কেন্দ্র করে ২০২৪ সালের ১ নভেম্বর নেটফ্লিক্সে মুক্তি পায় তথ্যচিত্র ‘ইটস অল ওভার: দ্য কিস দ্যাট চেঞ্জড স্প্যানিশ ফুটবল’। বিশ্বকাপ জয়ের আনন্দ থেকে বিতর্কের ঝড়
২০২৩ সালের নারী বিশ্বকাপের ফাইনালে ইংল্যান্ডকে হারিয়ে চ্যাম্পিয়ন হয় স্পেন। ট্রফি বিতরণ অনুষ্ঠানে খেলোয়াড়দের গলায় পদক পরিয়ে দিচ্ছিলেন স্প্যানিশ ফুটবল ফেডারেশনের তৎকালীন সভাপতি লুইস রুবিয়ালেস। সেই সময় তিনি স্পেনের তারকা ফুটবলার হেনি হেরমোসোকে জড়িয়ে ধরে ঠোঁটে চুমু খান। ঘটনাটি টেলিভিশনের ক্যামেরায় ধরা পড়ে এবং মুহূর্তেই সারা বিশ্বের সংবাদমাধ্যমে ছড়িয়ে পড়ে। পরে ইনস্টাগ্রাম লাইভে হেনি হেরমোসো জানান, ওই চুম্বন তাঁর অনিচ্ছাকৃত ছিল এবং তিনি সেটি পছন্দ করেননি। এরপরই শুরু হয় বিতর্ক, প্রতিবাদ এবং জবাবদিহির দাবি।
‘সে আকাবো’—এক আন্দোলনের জন্ম স্প্যানিশ ভাষায় ‘সে আকাবো’ অর্থ—‘এবার শেষ’ বা ‘আর নয়’। স্পেন দলের অন্যতম সেরা ফুটবলার অ্যালেক্সিয়া পুতেয়াস প্রথম এই স্লোগান ব্যবহার করেন। তিনি এবং তাঁর সতীর্থরা ঘোষণা দেন, ফুটবল ফেডারেশনের নেতৃত্বে পরিবর্তন না এলে তাঁরা জাতীয় দলে ফিরবেন না।
সামাজিক যোগাযোগমাধ্যমে দ্রুত ভাইরাল হয়ে যায় ‘সে আকাবো’ হ্যাশট্যাগ। কেবল ফুটবলার নয়, বিশ্বের বিভিন্ন দেশের ক্রীড়াবিদ, জাতিসংঘ, স্পেন সরকার এবং সাধারণ মানুষও এই আন্দোলনের সঙ্গে সংহতি প্রকাশ করেন।




 """

# Model Generate Process For Testing

In [67]:
gen_args = {
    "length_penalty": 1.8,
    "num_beams": 8, 
    "max_length": 32,
    "min_length": 20,
    "no_repeat_ngram_size": 3,
    "early_stopping": True
}


inputs = tokenizer(
            "summarize news: " + test_dialogue,
            truncation=True,
             return_tensors="pt"
            
)

inputs = {k:v.to(device) for k,v in inputs.items()}
model.eval()

with torch.no_grad():
    summarise_ids = model.generate(
        **inputs,
        **gen_args
    )

summary =tokenizer.decode(summarise_ids[0],skip_special_tokens=True)
print(summary)

বাংলাদেশের রাজধানী ঢাকায় একটি বেসরকারি বিশ্ববিদ্যালয়ে পড়ার সময় আমার বয়স ছিল ১২ বছর। আমার বয়স যখন ১২ বছর, তখন আমার সহপাঠীদের মধ্যে অনেকেই ইমেল ব্যবহার করতেন।

In [ ]:
tokenizer.save_pretrained("final_tokenizer")
model.save_pretrained("final_model",safe_serialization=True)

# Zip Model For Use

In [ ]:
import shutil
shutil.make_archive(
    "/kaggle/working/final_model",
    "zip",
    "/kaggle/working/final_model",
    
    
)

# Zip Tokenizer For Use

In [ ]:
import shutil
shutil.make_archive(
    "/kaggle/working/final_tokenizer",
    "zip",
    "/kaggle/working/final_tokenizer",
    
    
)

In [ ]:
from kaggle_secrets import UserSecretsClient

user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")

print("Secret loaded successfully!") # The actual token won't be printed for security

In [ ]:
from kaggle_secrets import UserSecretsClient
from huggingface_hub import HfApi, login

# Load your token
user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_TOKEN")

# Login to Hugging Face
login(token=hf_token)

# Get your username (to confirm login worked)
api = HfApi()
user_info = api.whoami()
username = user_info['name']
print(f"✅ Logged in as: {username}")

# Create a repository for your model
repo_id = f"{username}/bengali-text-summarizer"
api.create_repo(repo_id=repo_id, exist_ok=True)
print(f"✅ Repository created: {repo_id}")

# Upload your file - FIXED the spacing
print("📤 Uploading final_model.zip (this may take several minutes for 940MB)...")
api.upload_file(  # ✅ Removed spaces
    path_or_fileobj="/kaggle/working/final_model.zip",
    path_in_repo="final_model.zip",
    repo_id=repo_id,
)
print(f"✅ Upload complete!")
print(f"📍 View your model at: https://huggingface.co/{repo_id}")